Gulaschsuppe
------------

* Vorbereitung: ca. 20 Minuten
* Zubereitung: ca. 80 Minuten

Zutaten
~~~~~~~

* 2 Zwiebeln
* 2 Knoblauchzehen
* 2 rote Paprikaschoten
* 400 g Rindfleisch (Schulter/ Tafelspitz)
* 3 EL Öl
* 1 EL Mehl
* 1 EL Tomatenmark
* 1 TL Paprikapulver
* 200 ml Rotwein
* 1 l Rinderbrühe (instant)
* 1/2 TL gemahlener Kümmel
* 1 TL frischer Majoran
* Salz, Pfeffer

Zubereitung
~~~~~~~~~~~

1.  Die Zwiebeln und den Knoblauch abziehen und fein würfeln. Die Paprikaschoten halbieren, putzen, entkernen, waschen und in 1 cm große Stücke schneiden. Das Fleisch abbrausen, trocken tupfen und in 1 cm große Würfel schneiden.
2.  Das Öl in einem großen Topf erhitzen, das Fleisch darin anbraten und mit Mehl bestäuben. Die Zwiebeln und die Paprika hinzufügen und 3 Minuten dünsten. Den Knoblauch und das Tomatenmark hinzufügen und kurz weiterbraten. Mit Paprikapulver bestäuben und mit Wein und Brühe ablöschen. Kümmel und Majoran dazugeben und alles ca. 75 Minuten köcheln lassen.
3.  Die Suppe mit Salz, Pfeffer und Paprikapulver abschmecken und evtl. mit Weißbrot servieren.
