= Käse-Lauch-Suppe mit Hackfleisch

- Vorbereitung: ca. 15 Minuten
- Zubereitung: ca. 20 Minuten

== Zutaten
    
- 500 g Hackfleisch, gemischt
- 3 Stangen Lauch
- 250 g Schmelzkäse
- 1 Becher Crème fraîche, ca. 150 g
- 3 Würfel Gemüsebrühe
- 700 ml	Wasser
- 2 Baguettes, zum Aufbacken
- 3 EL Öl
- Muskat
- 1 Knoblauchzehe
- 1 Zwiebel


== Zubereitung

- Den Ofen auf 175° Celsius vorheizen. Die Baguettes in den vorgeheizten Ofen legen und ca. 10 Minuten backen.

- Derweil Öl in einen großen Topf geben. Die klein geschnittene Zwiebel und Knoblauch darin glasig dünsten. Das Hackfleisch zugeben und von allen Seiten gut anbraten. Mit Salz und Pfeffer würzen. Den Lauch in kleine Ringe schneiden und zum Hackfleisch geben. Ca. 5 Minuten mit anbraten. Das Wasser zugießen, Brühwürfel hineingeben und alles ca. 10 Minuten auf kleiner Flamme köcheln lassen.

- Den Schmelzkäse einrühren und schmelzen lassen. Crème fraîche einrühren und noch einmal kurz aufkochen lassen. Die Suppe mit Salz, Pfeffer und Muskat kräftig abschmecken.

- Die Baguettes in Scheiben schneiden und zu der Suppe reichen.

---

Quelle: https://www.chefkoch.de/rezepte/982031203667502/Kaese-Lauch-Suppe-mit-Hackfleisch.html
