= Blumenkohl-Auflauf 2

* Zubereitung: ca. 20 Minuten
* Garzeit: ca. 25 Minuten
* Für 4 Portionen

== Zutaten

* 1 Blumenkohl
* 1 kg Kartoffeln, mehlig kochend
* 1 Becher Schmelzkäse, 9%
* 1 Becher Cremefine zum Kochen
* 200 g Käse, gerieben
* 2 Zwiebeln
* 2 Knoblauchzehen
* Majoran
* Liebstöckel

== Zubereitung

- Die Kartoffeln schälen und in feine Scheiben schneiden. In Salzwasser
zum Kochen bringen und bissfest garen. In dieser Zeit den Blumenkohl in
kleine Röschen zerteilen und waschen. Die Kartoffeln abgießen und
nochmal Wasser zum Kochen bringen. Dann die Röschen 5 Minuten leicht
köcheln lassen und abgießen. Die Zwiebeln in Würfel schneiden und in
etwas Olivenöl anrösten. In einer Auflaufform erst die
Kartoffelscheiben, darauf die Blumenkohl-Röschen und oben darauf die
Röstzwiebeln verteilen.
- Den Schmelzkäse mit Cremefine glatt rühren. Eventuell noch mit etwas
Milch verlängern, je nachdem, wie viel Soße gewünscht ist. Die
Knoblauchzehen hinein pressen und mit wenig Salz, viel Pfeffer, Majoran
und Liebstöckel abschmecken. Die Soße über den Auflauf gießen. Den
geriebenen Käse darüber streuen und den Auflauf bei 180° Celsius 20 - 30
Minuten gratinieren.

Quelle:
https://www.chefkoch.de/rezepte/1284191233757670/Koestlicher-Blumenkohlauflauf.html