= Deftiger Knödelauflauf

* Zubereitung: ca. 25 Minuten
* Backzeit: ca. 45 Minuten
* Für 4 Portionen

== Zutaten

* 1 Packung Semmelknödel im Kochbeutel (6 Stück)
* 600 g Kohlrabi
* 600 g Möhren
* Muskatnuss
* 250 ml Milch
* 200 g Sahne
* 1 EL Butter
* 1 EL Mehl
* 3 Eier
* 150 g geriebener Gouda
* Fett für die Form

== Zubereitung

- Die Knödel nach Packungsangabe zubereiten, auskühlen lassen, in ca. 1
cm dicke Scheiben schneiden. Gemüse schälen, waschen. Kohlrabi
halbieren, wie die Möhren in 5 mm dicke Scheiben schneiden. Gemüse in
Salzwasser 5 Minuten vorkochen. Ofen auf 200° Celsius (Umluft: 180°
Celsius) vorheizen.
- Inzwischen die Milch mit Sahne vermischen. Butter in einem Topf
erhitzen, Mehl darin andünsten. Sahnemilch dazugießen. Unter häufigem
Rühren 5 Minuten köcheln lassen. Etwas abkühlen lassen. Eier einrühren,
mit Salz, Pfeffer und Muskat würzen.
- Die Hälfte der Knödel- und Gemüsescheiben dachziegelartig in eine
gefettete Auflaufform schichten. Mit der Hälfte Käse bestreuen.
Restliches Gemüse und Knödelscheiben als zweite Schicht darauflegen.
- Bechamel-Sauce über den Auflauf gießen, mit übrigem Käse bestreuen.
Auflauf im Ofen ca. 45 Minuten backen. Nach Belieben mit Kräutern
garnieren, servieren.
