= Enchiladas de Queso

* Zubereitung: ca. 35 Minuten
* Backzeit: ca. 30 Minuten
* Für 4 Personen

== Zutaten

* 8 Tortillas
* 400 g Käse, gerieben (Emmentaler und Gouda gemischt)
* 2 Zwiebeln
* 3 Paprika
* 400 g Creme fraîche
* 500 g Tomaten, passiert
* 1 Zehe Knoblauch
* 2 Chilischoten
* Salz
* Pfeffer
* Zitronensaft
* Zucker

== Zubereitung

- Die Zwiebeln schälen und fein hacken. In etwas Öl glasig dünsten. Die
Paprikaschoten putzen und ebenfalls klein würfeln, dann zu den Zwiebeln
in die Pfanne geben. Circa 10 Minuten lang in der Pfanne anbraten. Mit
Salz und Pfeffer würzen. Vom Herd nehmen und abkühlen lassen
- Für die Sauce:
Die Chilischoten längs halbieren und entkernen, dann fein hacken. 4 EL
der Zwiebel-Paprika-Masse zusammen mit den passierten Tomaten, den
Chilischoten, einem Esslöffel vom Creme fraiche und dem gepressten
Knoblauch in einem Topf erhitzen, dabei ab und zu rühren. Ca. 15 Minuten
lang köcheln lassen, dann mit Salz, Pfeffer, Zucker und einem Spritzer
Zitronensaft abschmecken.
- Für die Füllung:
Restliches Creme fraiche und 320g geriebenen Käse verrühren. Das
abgekühlte Gemüse ebenfalls unterrühren und die Masse mit Salz und
Pfeffer abschmecken.
- In eine rechteckige Auflaufform ca. 5 EL der Sauce geben und
gleichmäßig verteilen. In die Mitte jeder Tortilla etwas von der Füllung
geben und aufrollen. Mit der Naht nach unten in die Auflaufform legen.
Die Sauce gleichmäßig über den Tortillas verteilen und mit den
restlichen 80 g Käse bestreuen. Bei 180° Celsius ca. 25-30 Minuten
backen.

Quelle:
http://www.chefkoch.de/rezepte/1805181291909643/Enchiladas-de-Queso.html