= Farfalle mit Mozzarella und Pinienkernen

* Zubereitung: ca. 25 Minuten
* Für 2 Portionen

== Zutaten

* 25 g getrocknete Tomaten
* 150 g Farfalle
* 3 Stiele Oregano
* 2 EL Olivenöl
* 20 g Pinienkerne
* 125 g Büffelmozzarella

== Zubereitung

- Die getrockneten Tomate in eine kleine Schüssel geben und mit
kochendem Wasser übergießen. 15 Minuten einweichen.
- Die Nudeln nach Packungsanleitung in reichlich kochendem Salzwasser
bissfest garen. Inzwischen den Büffelmozzarella aus der Packung nehmen,
gut abtropfen lassen und in kleine Stücke reißen.
- Oregano unter fließendem kalten Wasser waschen, trockenschütteln, die
Blättchen abzupfen und fein hacken. Die eingeweichten Tomaten abgießen,
mit der Hand leicht ausdrücken und in grobe Würfel schneiden.
- Olivenöl in einer Pfanne erhitzen und Pinienkerne darin bei mittlerer
Hitze unter Rühren 2-3 Minuten leicht anbräunen. Tomatenwürfel dazugeben
und kurz mitdünsten. 2 EL vom heißen Nudelwasser unterrühren.
- Gegarte Nudeln abgießen und gut abtropfen lassen. Die Nudeln in die
Pfanne geben und mit den Pinienkernen und Tomatenstücken vermischen. Zum
Schluss Mozzarella und Oregano untermischen. Alles mit Salz und Pfeffer
würzen und sofort servieren.
