= Fladenbrot-Pizza

- Zubereitung: ca. 25 Minuten
- Backen: ca. 15 Minuten
- Für 2 Personen

== Zutaten

- 1 Knoblauchzehe
- 1 TL Oregano
- 5 EL Olivenöl
- 350 g Strauchtomaten
- 125 g Mozzarella
- 1 Fladenbrot, ca. 20 cm Durchmesser
- 3 Stiele Basilikum
- 40 g Rauke
- 40 g Parmesan
- 2 EL Aceto balsamico

== Zubereitung

- Den Ofen auf 220° Celsius (Umluft nicht empfehlenswert) vorheizen.
Knoblauch fein hacken. Mit Oregano und Öl verrühren. Von den Tomaten den
Stielansatz entfernen. Tomaten in Scheiben schneiden. Mozzarella gut
abtropfen lassen, halbieren und in dünne Scheiben schneiden.
- Fladenbrot mit einem großen Sägemesser waagerecht halbieren.
Brothälften mit den Schnittflächen nach oben auf ein mit Backpapier
belegtes Blech legen. Brote mit der Hälfte des Würzöls beträufeln. Mit
Tomaten- und Mozzarellascheiben belegen und mit dem restlichen Öl
beträufeln.
- Im heißen Backofen auf der mittleren Schiene 15 Minuten backen.
Inzwischen Basilikumblätter von den Stielen zupfen. Rauke putzen und
waschen. Parmesan mit einem Sparschäler in Scheiben hobeln.
- Fladenbrotpizza aus dem Ofen nehmen. Mit Salz und Pfeffer würzen, mit
Basilikum, Rauke und Parmesan bestreuen und sofort mit Essig beträufelt
servieren