= Gebackener Gemüse-Couscous

* Zubereitung: ca. 20 Minuten
* Backen: ca. 20 Minuten
* Für 4 Portionen

== Zutaten

* 200 g Champignons
* 1/2 Salatgurke
* 200 g Feta
* 4 Tomaten
* 1 Dose Mais (285 g Abtropfgewicht)
* 500 g Putenbrust
* 4 EL Rapsöl
* 200 g Couscous
* 150 g Ajvar
* 600 ml Hühnerbrühe
* Minze zum Garnieren

== Zubereitung

- Den Backofen auf 225° Celsius (Umluft 200° Celsius) vorheizen. Die
Pilze putzen und in Scheiben schneiden. Die Gurke schälen, entkernen und
würfeln. Feta zerbröckeln. Die Tomaten waschen, halbieren, entkernen und
würfeln. Den Mais abgießen.
- Das Fleisch abbrausen, trocken tupfen, in Scheiben schneiden. 2 EL Öl
in einer großen Pfanne erhitzen, das Fleisch darin anbraten. Pilze, Mais
und Gurke hinzufügen, salzen und pfeffern, kurz mitbraten.
- Den Couscous in eine mit Öl gefettete Auflaufform (ca. 25x35 cm)
geben. Mit Tomaten, Ajvar und der heißen Brühe verrühren. Den
Putenbrust-Mix und die Hälfte vom Schafskäse unterheben. Couscous mit
Salz und Pfeffer würzen, mit dem übrigen Käse bestreuen und im Backofen
ca. 15 bis 20 Minuten backen. Mit der Minze garniert servieren.