= Gnocchi mit Tomaten und Blattspinat

* Zubereitung: ca. 20 Minuten
* Für 2 Personen

== Zutaten

* 350 g Gnocchi, frisch
* 150 g Blattspinat (TK)
* 2 große Tomaten
* 1 kleine Zwiebel
* 1 Knoblauchzehe
* 1 EL Tomatenmark
* 1/4 TL Brühe, gekörnt
* 4 EL Sahne
* 1 Prise Zucker
* 1 EL Öl, neutral

== Zubereitung

- Die Gnocchi nur ganz kurz in kochendes Salzwasser geben. Sofort
herausholen, kurz kalt abbrausen und gut abtropfen lassen, beiseite
stellen.
- Den aufgetauten Blattspinat gut ausdrücken und etwas kleiner
schneiden. Die Tomaten häuten, den harten Strunk entfernen. Die Tomaten
in kleine Stücke schneiden, dabei das Tomatenwasser auffangen. Die
Zwiebel fein würfeln und den Knoblauch fein hacken.
- Das Öl in einer beschichteten Pfanne erhitzen und die Gnocchi
rundherum leicht anbraten. Die Zwiebelwürfel und den Knoblauch
hinzugeben und kurz mitdünsten, bis die Zwiebeln glasig sind.
Tomatenmark zugeben und unter Rühren ca. 1 Minute anbraten.
- Mit den Tomatenstücken und dem Tomatenwasser ablöschen, gekörnte Brühe
hinzufügen. Mit Zucker abschmecken und ca. 5 Minuten köcheln lassen.
Falls zu viel Flüssigkeit verkocht, hin und wieder mit wenig Wasser
auffüllen. Die Tomatenstücke sollten anfangen zu "schmelzen".
- Den Blattspinat hinzugeben und nur kurz erwärmen. Mit Sahne, Salz und
Pfeffer abschmecken und sofort servieren.

Quelle:
https://www.chefkoch.de/rezepte/2222001355649326/Gnocchi-mit-Tomaten-und-Blattspinat.html