= Kreolischer Linseneintopf mit Paprika

== Zutaten

* 300 g Linsen, kleine, grüne
* 1 Lorbeerblatt
* 1 Liter Gemüsebrühe
* 1 Zwiebel, rot
* 4 Zehen Knoblauch
* 2 Chilischoten, grün
* 400 g Tomaten, geschält, abgetropft
* 4 EL Olivenöl
* 40 g Mehl
* 2 EL Sojasauce
* 2 EL Tomatenmark
* 1 TL Paprikapulver, edelsüß
* 1/2 TL Oregano
* 1/2 TL Thymian
* 2 Paprikaschoten, rot
* 2 Paprikaschoten, gelb

== Zubereitung

- Den Backofen auf 200° C vorheizen. Die Paprika auf Alu-Folie auf den
Rost legen und mit zusätzlicher Alu-Folie zudecken. Nach 20 Minuten
sollte die Haut teilweise verkohlt sein, dann in eine Schüssel legen,
abdecken und die Paprika dort auskühlen lassen.
- Die Linsen in ein Sieb geben und unter fließendem Wasser waschen, zur
Gemüsebrühe geben, aufkochen und 10 Minuten weiterkochen. Dann abseihen
und die Brühe auffangen.
- Die Zwiebel und die Knoblauchzehen schälen und hacken. Die
Chili-Schoten putzen und hacken, ebenso die Tomaten zerkleinern.
- Das Olivenöl erhitzen, Mehl dazugeben und unter Rühren leicht
anbräunen. Unter Rühren Zwiebel, Knoblauch und Chili dazugeben und mit
Sojasauce löschen. Tomatenmark und Paprikapulver dazugeben, leicht
erhitzen und Tomaten dazugeben. Mit der Brühe aufgießen, mit Thymian und
Oregano würzen. Glatt rühren und 15 Minuten köcheln lassen.
- Der abgekühlten Paprika mit einem spitzen Messer die Haut abziehen und
den Saft auffangen. Paprika halbieren, Kerne rausholen und in Streifen
schneiden. Linsen in die Sauce geben, weiter 5 Minuten köcheln und vom
Herd nehmen. Paprikasaft einrühren, salzen und in einer Schüssel
anrichten, mit den Paprika garnieren.
