= One Pot Pasta Thai-Style mit Gemüse und Erdnüssen

* Zubereitung: ca. 10 Minuten
* Kochzeit: ca. 15 Minuten
* Für 4 Personen
  
== Zutaten

* 400 g Linguine
* 1 l Gemüsebrühe
* 60 ml Wasser
* 4 Knoblauchzehen
* 5 cm Ingwer
* 1 Möhre
* 1 rote Paprika
* 4 Frühlingszwiebeln
* 125 g geröstete Erdnüsse + 25 g zum Dekorieren
* 2 Esslöffel Erdnussbutter
* 1/2 Teelöffel Chiliflocken
* 1 Esslöffel Sojasauce
* 3 Zweige Koriander
* Saft von 2 Limetten


== Zubereitung

- Knoblauchzehen schälen und fein hacken. Ingwer in ca. 2-3 cm große Scheiben schneiden. Möhre schälen, quer halbieren und in feine Streifen schneiden. Paprika waschen, entkernen und in dünne Streifen schneiden. Frühlingszwiebeln waschen, dunkelgrünen Teil entfernen und längs in schmale Streifen schneiden.

- Für die Pasta alle Zutaten, bis auf Koriander und Limettensaft, in einen großen Topf geben und zum Kochen bringen. Hitze reduzieren und ohne Deckel 10 Minuten köcheln lassen, gelegentlich umrühren. Wenn die Nudeln nach Ablauf der Kochzeit noch nicht weich sind, 50 ml Wasser dazugeben und erneut 3-5 Minuten köcheln lassen. Mit Salz und Pfeffer würzen.

- Koriander waschen, trocken schütteln und fein hacken. Restliche Erdnüsse fein hacken. Ingwerstücke aus dem Topf nehmen.

- Koriander und Limettensaft in den Topf geben und verrühren. Vor dem Servieren mit Erdnüssen und Koriander garnieren.

---

Quelle: https://www.springlane.de/magazin/rezeptideen/one-pot-pasta-thai-style-mit-gemuese-und-erdnuessen/