= Ratatouille

* Zubereitung: ca. 30 Minuten
* Kochen: ca. 30 Minuten
* Für 4 Personen

== Zutaten

* 1 Aubergine
* 2 Zucchini
* 2 rote Paprikaschoten
* 2 gelbe Paprikaschoten
* 1 Dose geschälte Tomaten (ca. 850 ml)
* 1 Gemüsezwiebel
* 4 Knoblauchzehen
* 1 TL gehackter Rosmarin
* 1 EL gehackter Thymian
* 1 EL gehackter Salbei
* 2 EL Zucker
* 100 ml Olivenöl
* Salz, Pfeffer
* 1/2 Tube Tomatenmark

== Zubereitung

- Das Gemüse waschen, putzen und in mundgerechte Stücke schneiden. Die
Zwiebel grob würfeln, den Knoblauch fein hacken. Die Auberginenstücke
einsalzen, ca. 10 Minuten ziehen lassen und dann gründlich abtupfen.
- In einer großen Pfanne mit hohem Rand das Olivenöl erhitzen. Zwiebeln
und Zucchini darin anbraten, Paprika zugeben und als letztes die
Aubergine zufügen. Etwas 5 Minuten kräftig braten. Tomatenmark zugeben
und unterrühren, salzen und pfeffern, Knoblauch und Kräuter sowie die
geschälten Tomaten und den Zucker dazugeben.
- Den Herd auf mittlere Flamme stellen und das Ratatouille etwa 20
Minuten köcheln lassen, wenn nötig etwas Wasser zufügen.