= Rosenkohlauflauf

* Zubereitung: ca. 25 Minuten
* Backen: ca. 35 Minuten
* Für 2 Personen

== Zutaten

* 500 g Rosenkohl
* 1/2 Bio-Zitrone
* 4 Zweige Thymian
* 1 kleine rote Zwiebel
* 125 g Ricotta
* 2 Eier, Größe M
* 3 EL frisch geriebener Parmesan
* Chilipulver
* 1 EL Pinienkerne
* 1/2 EL Butter
* Salz

== Zubereitung

- Den Rosenkohl waschen. Welke Blätter und den Strunkansatz entfernen.
Rosenkohl je nach Größe halbieren oder vierteln und in kochendem
Salzwasser 2 Minuten vorkochen. In einem Sieb kurz kalt abschrecken und
abtropfen lassen.
- Den Backofen auf 180° Celsius vorheizen. Die Zitronenhälfte heiß
waschen und abtrocknen. Die Schale dünn abschneiden und in feine
Streifen schneiden. Thymian waschen und trocken schütteln. Die Blättchen
abzupfen. Die Zwiebel schälen und fein würfeln.
- Den Rosenkohl mit Zitronenschale, Thymian und Zwiebel mischen und in
eine ofenfeste Form geben. Den Ricotta mit den Eiern und Käse verrühren
und mit Salz und einer Prise Chilipulver abschmecken. Über den Rosenkohl
verteilen. Die Pinienkerne und die Butter in Flöckchen aufstreuen. Den
Auflauf im Ofen (Mitte, 160° Celsius Umluft) circa 35 Minuten backen,
bis er gebräunt ist.