= Salatfladen mit Gorgonzola

* Für 1 Springform (26 cm Durchmesser)
* Zubereitung: ca. 35 Minuten
* Ruhen: 50 Minuten
* Backen ca. 20 Minuten
* Bei 6 Stücken pro Stück: ca. 320 kcal

== Zutaten

=== Für den Teig

* 125 g Weizenmehl + Mehl für die Arbeitsfläche
* 100 g Dinkelvollkornmehl
* 1/2 TL Trockenhefe

=== Für den Belag

* 200 g gemischte bittere Salate (z.B. Rucola, Radicchio und Endivie)
* 2 Knoblauchzehen
* 2 EL Olivenöl
* 150 g Gorgonzola
* 4 EL frisch geriebener Parmesan
* 2 EL Pinienkerne

=== Ausserdem

* Öl für die Form

== Zubereitung

- Für den Hefeteig beide Mehlsorten in einer Schüssel mit der Hefe und
je 1 Prise Zucker und Salz vermischen. Ca. 150 ml lauwarmes Wasser
dazugießen und alles zu einem weichen Teig verkneten. Zugedeckt an einem
warmen Ort ca. 40 Minuten gehen lassen, bis sich das Teigvolumen
verdoppelt hat.
- Die Salatblätter waschen, trocken schleudern und - bis auf den Rucola - in feine Streifen schneiden. Den Knoblauch schälen und klein würfeln.
Das Olivenöl in einer Pfanne erhitzen und Salat und Knoblauch darin
braten, bis der Salat zusammenfällt. Mit Salz und Pfeffer würzen.
- Die Springform mit Öl fetten. Den Teig auf wenig Mehl zu einem Kreis
von ca. 26 cm Durchmesser ausrollen. Teig in die Form legen und
zugedeckt nochmals ca. 10 Minuten gehen lassen. Den Backofen auf 220°
Celsius vorheizen.
- Die Knoblauch-Salat-Mischung auf dem Teig verteilen. Den Gorgonzola
zerbröckeln oder in Stückchen schneiden und auf den Fladen geben.
Parmesan und Pinienkerne ebenfalls daraufstreuen. Den Fladen im heißen
Ofen (Mitte, Umluft 200° Celsius) in 15 bis 20 Minuten goldbraun backen.
