= Spicy Thai Noodles


* Zubereitung: ca. 15 Minuten
* Kochzeit: ca. 15 Minuten
* Für 2 Personen

== Zutaten

- 500 g	Gemüse (z.B. Paprika, Zucchini, Möhren, Erbsen, Frühlingszwiebel)
- 250 g	Mandel-Nuss-Tofu oder Huhn
- 250 g	Konjaknudeln

=== Für die Sauce

- 2	Knoblauchzehen, gepresst
- 1 EL	Chilisauce (Sriracha)
- 2 EL Chilisauce, süß
- 2 EL Sojasauce
- 2 EL Erdnussbutter
- 1 Spritzer Limettensaft

=== Zum Bestreuen
- 2 EL	Erdnüsse, gehackt oder ganz
- n. B.	Koriander, frisch gehackt

== Zubereitung

- Das gewaschene und geschnittene Gemüse in einer größeren Pfanne anbraten. Dann den Tofu bzw. das Hühnerfleisch in mundgerechten Stücken dazugeben und mitbraten.

- Bei der Soße kann man mit den Mengen nach Belieben ausprobieren, aber es sollte nichts weggelassen werden. Alles vermischen und unter das Gemüse heben, ggf. etwas Wasser dazugeben.

- Die Konjaknudeln heiß abgewaschen und abgetropft. Die Nudeln einfach noch leicht feucht unter die Gemüse-Erdnussmischung heben und noch weitere 5 Min. leicht mitbraten.

- Mit gehackten Erdnüssen und Koriander bestreuen und servieren.

---

Quelle: https://www.chefkoch.de/rezepte/3570031535729583/Spicy-Thai-Noodles.html
