= Spinat-Risoto


* Zubereitung: ca. 35 Minuten
* Für 4 Personen

== Zutaten

- 800 ml Gemüsebrühe
- 2 Zwiebeln
- 4 EL Olivenöl
- 300 g Risottoreis (Arborio oder Vialone)
- 2 Knoblauchzehen
- 2 EL Butter
- 200 g Blattspinat (TK), einmal grob gehackt
- 200 ml süße Sahne
- 100 g Parmesan, frisch geriebener


== Zubereitung

- Die Brühe aufkochen lassen. Inzwischen die Zwiebeln halbieren, schälen und in feine Würfel schneiden.

- In einem Topf das Öl heiß werden lassen und die Zwiebeln darin sanft anbraten, ohne dass sie braun werden. Dann den Reis zugeben und 1 Minute unter Rühren mitbraten. Die ganze Brühe dazu gießen. Salzen und kräftig durchrühren. Aufkochen lassen und den Deckel auf den Topf legen. Hitze auf geringste Stufe zurückstellen und das Risotto ca. 15 Minuten lang ungerührt vor sich hin köcheln lassen.

- In der Zwischenzeit Knoblauch schälen und durch die Presse drücken. Im jetzt leeren Kochtopf, in dem vorher die Brühe gewesen ist, die Butter schmelzen. Den Knoblauch darin kurz anbraten und den Spinat samt Sahne dazu geben. Leicht salzen und zugedeckt so lange köcheln lassen, bis der Spinat aufgetaut und die Sahne fast eingekocht ist.

- Nun das Risotto kontrollieren, das jetzt ein nicht zu suppiger Brei mit angenehm festen Reiskörnern sein sollte. Ist es noch zu flüssig, kurz ohne Deckel weiter kochen lassen - aber dabei nicht rühren. Dann den Rahmspinat und Parmesan dazugeben und jetzt kräftig rühren. Heiß servieren.

---


Quelle: https://www.chefkoch.de/rezepte/682951170826060/Spinat-Risotto.html
