= Spinat-Lasagne


* Zubereitung: ca. 20 Minuten
* Backzeit: ca. 45 Minuten
* Für 4 Personen
  
== Zutaten

- 800 g Spinat, frisch blanchiert
- 2 Zwiebeln, mittelgroß
- 2	Knoblauchzehen
- 400 g	Tomaten, passiert
- 2 EL Tomatenmark
- 2 EL Kräuter, gemischt
- Öl
- 350 g	Frischkäse, light
- 100 g	Parmesan
- Muskat
- Paprikapulver
- Lasagneplatten


== Zubereitung

- Zwiebel und Knoblauch fein würfeln, 2 EL Öl erhitzen und je die Hälfte von Zwiebeln und Knoblauch darin anbraten. Den Spinat unterrühren und heiß werden lassen, zum Schluss den Frischkäse unterrühren. Mit Muskatnuss, Salz und Pfeffer abschmecken.

- 2 EL Öl erhitzen, die restlichen Zwiebeln und den restlichen Knoblauch darin anbraten, Tomatenmark und Kräuter dazu geben, kurz durchrösten und mit den passierten Tomaten aufgießen. Ca. 5 Minuten köcheln lassen und mit Salz, Pfeffer und Paprikapulver abschmecken.

- Eine Auflaufform fetten, etwas Tomatensauce darin verteilen, dann Lasagneplatten, Spinat, Tomatensauce und wieder Lasagneplatten Schicht für Schicht in die Form füllen, mit Tomatensauce abschließen. Mit Parmesan bestreuen und im vorgeheizten Backrohr bei 175° Celsius Umluft 40 - 45 Minuten backen.
---


Quelle: https://www.chefkoch.de/rezepte/1231981228220302/Spinatlasagne.html