= Spitzkohl-Curry

* Vorbereitung: ca. 25 Minuten
* Zubereitung: ca. 30 Minuten
* Für 4 Personen

== Zutaten

* 1 kleiner Spitzkohl, ca. 600 g
* 3 Kartoffeln, mittelgroß
* 3 Möhren
* 1 Zwiebeln
* 1 Knoblauchzehe
* 1 Stück Ingwer, ca. 2 cm
* 1 Chilischote
* 2 EL Öl
* 1 EL Curry
* Kreuzkümmel
* 200 ml Kokosmilch
* 250 ml Gemüsebrühe
* 100 g Linsen, rot

== Zubereitung

- Den Spitzkohl vierteln, Strunk entfernen, Viertel in Streifen
schneiden. Geschälte Kartoffeln würfeln, Möhren in Scheiben schneiden,
Zwiebel und Knoblauch fein hacken, Ingwer reiben. Chilischote ohne Kerne
und Trennwände fein würfeln.
- Im erhitzten Öl das vorbereitete Gemüse andünsten, Curry und
Kreuzkümmel zugeben und kurz mitdünsten. Kokosmilch und etwas
Gemüsebrühe zugießen, zehn Minuten zugedeckt köcheln. Die Linsen zugeben
und weitere ca. zehn Minuten garen (siehe Packungsangabe). Falls
notwendig, die restliche Brühe nach und nach zugeben. Das Curry sollte
eher trocken sein. Mit Salz, Pfeffer und Zucker abschmecken.

---

Quelle: https://www.chefkoch.de/rezepte/2033501329494843/Spitzkohl-Curry.html