= Tomaten-Tarte mit Ziegenkäse

* Zubereitung: ca. 25 Minuten
* Backzeit: ca. 45 Minuten
* Für 1 Springform (30 cm Durchmesser)

== Zutaten

* 1 Rolle Blätterteig (ca. 250g, aus dem Kühlregal)
* 500g Kirschtomaten
* 100g getrocknete Tomaten
* Kräutersalz
* Pfeffer
* je ein kleiner Zweig Rosmarin und Thymian
* 100g Parmesan
* 200g Ziegenfrischkäse
* 150g Schmand
* 2 Eier (Größe M)
* 3 EL Pinienkerne
* Mehl für die Arbeitsfläche

== Zubereitung

- Springform mit Backpapier auslegen. Teig auf wenig Mehl ausrollen, die
Form damit auslegen, dabei einen 2cm hohen Rand bilden. Teigboden mit
einer Gabel mehrfach einstechen. Den Ofen auf 180° Celsius vorheizen.
- Kirschtomaten waschen, abtrocknen, halbieren und auf dem Teig
verteilen; leicht salzen und pfeffern. Die getrockneten Tomaten in feine
Streifen schneiden, darüber verteilen.
- Kräuter waschen, die Nadeln bzw. Blättchen klein schneiden. Parmesan
grob raspeln. Frischkäse, Schmand und Eier mit den Kräutern und Parmesan
verrühren, mit Salz und Pfeffer würzen, über die Tarte gießen. Im heißen
Ofen (Mitte. Umluft 160° Celsius) ca. 30 Minuten backen. Pinienkerne
darüberstreuen und in 10-15 Minuten fertig backen.