= Tomatenrisotto


* Zubereitung: ca. 15 Minuten
* Kochzeit: ca. 25 Minuten
* Für 4 Personen
  
== Zutaten

- 1	Knoblauchzehe
- 2	Zwiebeln
- 1 Liter Gemüsefond
- 1 EL Butter
- 1 EL Olivenöl
- 350 g	Risottoreis
- 1 Dose Tomaten, stückig (ca. 400 g)
- 1/2 TL Chili, grob geschrotet
- 100 ml Weißwein
- 125 g Büffelmozzarella
- 1/2 Bund Basilikum
- 40 g Parmesan


== Zubereitung

- Knoblauch und Zwiebeln schälen und in feine Würfel hacken. Den Gemüsefond erhitzen.

- Butter und Olivenöl in einem Topf erhitzen, Zwiebeln und Knoblauch darin anschwitzen. Den Reis zugeben und unter Rühren so lange dünsten, bis er glasig wird. Weißwein angießen und unter Rühren verdampfen lassen.

- Tomaten und Chili zugeben und das Risotto mit Salz würzen. Nach und nach immer so viel Fond angießen, dass der Reis stets mit Flüssigkeit bedeckt ist. Den Reis ständig umrühren, ca. 25 Min. garen bzw. bis die ganze Flüssigkeit verbraucht ist.

- Mozzarella abtropfen lassen und in feine Streifen schneiden. Das Basilikum hacken. Den Parmesan reiben und direkt, nachdem das Risotto fertig ist, unterheben. Dann das gehackte Basilikum. Mit Salz und Pfeffer abschmecken, mit den Mozzarellastreifen und Basilikumblättern garnieren.

---

Quelle: https://www.chefkoch.de/rezepte/1715991280342456/Tomatenrisotto.html