= Zucchini-Käse-Quiche

* Zubereitung 30 Minuten
* Kühlzeit 60 Minuten
* Backzeit ca. 30 Minuten
* Für 1 Tarteform (28 cm Durchmesser)

== Zutaten

* 300 g Mehl und Mehl zum Arbeiten
* 150 g kalte Butter
* 500 g Zucchini
* 1 Zwiebel
* 2 Knoblauchzehen
* 2 EL Öl und Fett für die Form
* 4 Zweige Thymian
* 1 Dose weiße Bohnen (250g)
* 200 g Creme fraiche
* 3 Eier, Größe M
* 150 g Bergkäse, gerieben

== Zubereitung

* Mehl mit Butter, 1 TL Salz und 3-4 EL kaltem Wasser zu einem glatten Teig verkneten.
Zugedeckt 60 Minuten kalt stellen.
* Zucchini waschen, putzen. 1/2 Zucchini längs in Scheiben hobeln. Übrige raspeln und salzen. Zwiebel und Knoblauch abziehen, hacken. Beides in 1 EL heißem Öl mit Thymian andünsten. Bohnen abbrausen, abtropfen lassen, zum Zwiebel-Mix geben, salzen und pfeffern.
* Backofen auf 220 Grad (Umluft: 200 Grad) vorheizen. Form fetten. Mürbeteig auf bemehlter
Fläche zu einem Kreis, etwas größer als die Form, ausrollen. Teig in die Form legen,
den Rand etwas begradigen.
* Raspel ausdrücken. Creme fraiche mit Eiern verrühren, salzen, pfeffern. Mit Käse, Zuc-
chiniraspeln und Bohnen-Mix (Thymianzweige vorher entfernen) mischen. Masse auf den
Teig geben. Zucchinischeiben mit restlichem ÖL (1 EL), Salz und Pfeffer mischen, einrollen, auf die Käsemasse setzen. Quiche im Ofen ca. 30 Minuten backen.
* Quiche aus dem Ofen nehmen, mindestens 10 Minuten ruhen lassen.
