= Kichererbsensalat mit getrockneten Tomaten und Feta

- Zubereitung: ca. 15 Minuten
- Ruhezeit: 1 Stunden
- Für 2 Personen

== Zutaten

- 1 Dose Kichererbsen, klein
- 1 kleine Zwiebel, geschnitten
- 1 Handvoll Tomaten, getrocknete, klein geschnitten
- 70 g Feta-Käse, klein gewürfelt
- 1 TL Sambal Oelek
- 1 Handvoll Petersilie, gehackt
- 4 EL Olivenöl
- 1 Zitrone, Bio
- 1 Zehe Knoblauch, gepresst
- Salz und Pfeffer


== Zubereitung

- Kichererbsen in einem Sieb abtropfen lassen und abspülen. In einer Schüssel
die Kichererbsen, Zwiebel, getrocknete Tomaten, den Feta und die Petersilie
vermischen. Etwas Schale der Bio-Zitrone dazu reiben. Die Zitrone danach
aufschneiden und auspressen.

- Öl, 2-3 EL Zitronensaft und Knoblauch zu einem Dressing vermischen. Unter den
Salat mischen und diesen dann mit Sambal, Salz und Pfeffer abschmecken. Den
Salat mindestens 30 Minuten ziehen lassen. Danach eventuell nochmal nachwürzen.

---

Quelle: https://www.chefkoch.de/rezepte/1287271234164583/Kichererbsensalat-mit-getrockneten-Tomaten-und-Feta.html
