= Reissalat Mexiko

* Zubereitung: ca. 30 Minuten
* Ruhezeit: ca. 2 Stunden
* Für 4 Portionen

== Zutaten

- 2 Tassen Reis
- 4 Tassen Gemüsebrühe
- 100 g	Erbsen, TK
- 2 Lauchzwiebeln
- 2	Paprikaschoten, rot oder gelb
- 150 g	Mais, aus der Dose
- 1 Dose	Kidneybohnen
- 2 EL Essig
- 3 EL Öl
- 7 EL Sahne
- 140 g	Tomatenmark
- Salz
- Zucker
- Cayennepfeffer
- Paprikapulver, edelsüß
- Kräuter (z. B. Thymian, Basilikum, Lavendel)
- 125 g Feta-Käse

== Zubereitung

- Den Reis in der Gemüsebrühe nach Packungsanweisung kochen, anschließend abkühlen lassen. Die Erbsen ca. 3 Minuten in Wasser kochen, abschrecken und auskühlen lassen. Die Paprikaschoten und die Lauchzwiebeln klein schneiden. Das Gemüse mit dem Reis mischen, Mais und Kidneybohnen unterheben.

- Für das Dressing Essig, Öl, Sahne und Tomatenmark miteinander verrühren. Mit Salz, Zucker, Cayennepfeffer, Paprikapulver und den Kräutern abschmecken. Unter den Reis und das Gemüse mischen, alles mindestens 2 Stunden (besser länger) ziehen lassen. Danach noch einmal abschmecken.

- Zum Servieren den zerbröckelten Fetakäse über den Reissalat geben.

Quelle: https://www.chefkoch.de/rezepte/1082051213947068/Reissalat-Mexico.html
