= Apfel-Zimt Fruchtriegel

* Zubereitung: ca. 20 Minuten
* Für 8 Stück

== Zutaten

* 125 g Mandeln
* 125 g getrocknete Äpfel
* 150 g getrocknete Datteln (entsteint)
* 1 Stück Ingwer (daumengroß)
* 1 EL Wasser
* 2 EL Zitronensaft
* 2 TL Zimt

== Zubereitung

- Die Mandeln in der Küchenmaschine, mit einem Mörser oder mit einem
Wiegemesser zerkleinern, so dass unterschiedliche große Stücke entstehen
(maximal 0,5 cm). Getrocknete Äpfel oder Apfelringe in kleinere Stücke
zerschneiden (maximal 1 cm). Den Ingwer schälen.
- Die Datteln gemeinsam mit dem Ingwer, Zitronensaft, Wasser und Zimt in
einen Standmixer geben und zerkleinern, bis eine zähe Paste entstanden
ist.
- Die Paste mit den Apfelstücken und den Mandeln in einer großen
Schüssel zu einer einheitlichen Masse verkneten.
- Eine flache Form mit Backpapier auslegen und die Masse darin - je nach
Wunsch - 1 bis 2 Zentimeter dick in Form drücken.
- Die Form für ca. 1 bis 2 Stunden zum Aushärten in den Kühlschrank
stellen. Anschließend herausnehmen und in Riegel schneiden.

--- 

Quelle: http://www.paleo360.de/rezepte/apfel-zimt-fruchtriegel/