= Buttermilchbrötchen

* Zubereitung: ca. 10 Minuten
* Backen: ca. 30 Minuten
* Für 12 Stück

== Zutaten

* 600 g Weizenmehl
* 1 Pck. Backpulver
* 1 gestr. TL Salz
* 2 TL Zucker
* 80 g Butter (zimmerwarm)
* 2 Eier
* 1 Eigelb
* 300 g Buttermilch

== Zubereitung

- Den Backofen auf 200° Celsius (Umluft: 180° Celsius) vorheizen. Für
den Teig Mehl mit Backpulver, Salz und Zucker in einer Rührschüssel
vermischen. Die Butter, Eier und 250 g Buttermilch hinzugeben. Die
Zutaten mit einem Mixer (Knethaken) zu einem glatten Teig verarbeiten
(etwa 2 Minuten).
- Den Teig aus der Schüssel nehmen, auf einer leicht mit Mehl bestäubten
Arbeitsfläche zu einer 8 - 10 cm dicken Rollen formen und mit einem sehr
scharfen Messer in 12 gleich große Scheiben schneiden (nicht drücken!).
- Die Teigstücke mit der Schnittfläche nach oben mit Abstand auf ein
Backblech (mit Backpapier belegt) legen. Zum Bestreichen Buttermilch mit
Eigelb verschlagen. Die Teigstücke damit bestreichen.
- Das Backblech in den vorgeheizten Ofen schieben. Die
Buttermilchbrötchen etwa 30 Minuten backen. Die Brötchen mit dem
Backpapier vom Backblech auf einen Kuchenrost ziehen. Brötchen erkalten
lassen.