= Caipirinha-Plätzchen

* Zubereitung: ca. 20 Minuten
* Backzeit: ca. 15 Minuten
* Für ca. 70 Stück

== Zutaten

=== Für den Teig

* 300 g Mehl
* 2 TL Backpulver
* 100 g Rohrzucker
* 1 Päckchen Vanillezucker
* 1 Ei
* 150 g Butter
* 2 TL Limettenschale

=== Für die Glasur

* 100 g Puderzucker
* 3 bis 4 EL Cachaca
* 2 EL Limettensaft
* 2 TL Limettenschale
* 1 EL Rohrzucker

== Zubereitung

- Das Mehl und Backpulver mischen. Rohrzucker, Vanillezucker, Ei,
gehackte Limettenschale und die kalte Butter in Stücken über das Mehl
verteilen. Den Teig mit dem Knethaken des Handrührers verkneten. Zum
Schluss den Teig mit der Hand zu einer glatten Kugel formen und ca. 30
Minuten kalt stellen.
- Den Teig ca. 1/2 cm dick ausrollen, ca. 5 cm große Kreise ausstechen
und auf ein mit Backpapier ausgelegtes Blech legen. Im vorgeheizten
Backofen bei 175 °C (Umluft: 150 °C) ca. 15 Minuten hellbraun backen.
- Für die Glasur Puderzucker und Cachaca glatt rühren. Limettensaft
zufügen und die abgekühlten Caipirinha-Plätzchen damit einpinseln.
Zuckerguss mit Limettenschale und Rohrzucker bestreuen.