= Fruchtige Blätterteig-Schnecken

* Zubereitung: 30 Minuten
* Backen: 18 bis 20 Minuten

== Zutaten

* 8 bis 10 Pflaumen
* 1 Packung Blätterteig (aus dem Kühlregal, ca. 275 g)
* 1 Päckchen Bourbon-Vanillezucker
* 1 Eigelb
* 50 g Butter
* 1/2 TL Zimtpulver
* 50 g Puderzucker

== Zubereitung

- Die Pflaumen waschen und halbieren, die Kerne entfernen. Die
Pflaumenhälften mit einem sehr scharfen Messer in 2 bis 3 mm dünne
Scheiben schneiden. Backofen auf 200° C (Umluft 180° C) vorheizen.
Backblech mit Papier belegen.
- Den fertig ausgerollten Blätterteig mit einem Teigrädchen oder
scharfen Messer in 10 bis 12 ca. 2 cm breite und 20 cm lange Streifen
schneiden. Die Pflaumenscheiben der Länge nach nebeneinander leicht
überlappend auf die Blätterteigstreifen legen und mit dem Vanillezucker
bestreuen.
- Das Eigelb leicht verquirlen. Die Enden der belegten
Blätterteigstreifen mit dem verquirlten Eigelb einpinseln. Die
Teigstreifen vorsichtig aufrollen, die Teigenden gut andrücken. Die
fertigen Pflaumen-Blätterteig-Schnecken jeweils auf das Backblech
setzen.
- Die Butter bei kleiner bis mittlerer Hitze in einem Topf schmelzen.
Das Zimtpulver und den Puderzucker dazugeben und unterrühren.
- Die Blätterteig-Schnecken mit der süßen Zimt-Butter einpinseln und im
heißen Ofen (Mitte) in 18 bis 20 Minuten goldbraun backen.
- Die Blätterteig-Schnecken aus dem Ofen nehmen und noch heiß servieren
oder auf einem Kuchengitter etwas abkühlen lassen.
