= Heidesand

* Zubereitung: ca. 45 Minuten
* Kühlzeit: ca. 2 Stunden
* Backzeit: ca. 12 Minuten
* Für ca. 50 Stück

== Zutaten

* 250 g Butter
* 1/2 Vanilleschote
* 350 g Mehl
* 1/2 TL Salz
* 200 g Zucker
* 1 TL Kakaopulver
* 3 EL Milch

== Zubereitung

- Die Butter bei kleiner Hitze zerlassen und leicht bräunen. Durch ein
Sieb in eine Schüssel gießen. Kalt stellen, bis die Butter wieder fest
geworden ist. Die Vanilleschote längs aufschneiden, Mark herausschaben.
Mehl, Vanillemark, Salz und Zucker mit Butter in Flöckchen rasch mit den
Händen zu einem glatten Teig verkneten.
- Den Teig halbieren und unter die eine Hälfte Kakaopulver und 1 EL
Milch kneten. Beide Teighälften zu gleich dicken Rollen (4 bis 5 cm
Durchmesser) formen, in Frischhaltefolie gewickelt 2 Stunden kalt
stellen.
- Beide Rollen der Länge nach vierteln. Jedes Viertel mit etwas Milch
bestreichen. Jeweils 4 Viertel zu einer Rolle zusammensetzen, so dass
sich je zwei helle und dunkle Viertel gegenüberliegen. Rollen in Folie
gewickelt 10 Minuten tiefkühlen.
- Den Ofen auf 180° Celsius (Umluft: 160° Celsius) vorheizen. Rollen in
4 mm dicke Scheiben schneiden. Auf ein mit Backpapier ausgelegtes Blech
legen, im Ofen ca. 12 Minuten backen. Herausnehmen und auskühlen lassen.