= Nussecken

* Zubereitung: ca. 30 Minuten
* Backzeit: ca. 25 - 30 Minuten
* Für 1 Backblech

== Zutaten

=== Für den Mürbeteig

- 300 g Mehl
- 130 g	Zucker
- 130 g	Butter
- 2	Eier
- 2 Pck. Vanillezucker
- 2 TL Backpulver, gestrichen

=== Für den Belag

- Aprikosenkonfitüre
- 200 g	Butter
- 200 g	Zucker
- 2 Pck. Vanillezucker
- 200 g	Haselnüsse, gemahlen
- 200 g	Haselnüsse, gehackt
- 4 EL Wasser
- 1 Tafel Kuvertüre

== Zubereitung

- Aus allen Zutaten einen glatten Teig kneten, auf einem mit Backpapier belegten Backblech ausrollen und anschließend mit Aprikosenmarmelade bestreichen.

- Für den Belag Butter, Zucker und Vanillezucker im Topf schmelzen. Die Nüsse mit dem Wasser unterrühren. Die Masse anschließend auf dem Teig verteilen. Im vorgeheizten Backofen bei 175 - 200° Celsius ca. 20 - 30 Minuten backen.

- Nach dem Backen die Nussecken schneiden. Auf dem Blech etwas abkühlen lassen. Nach dem Erkalten die Ecken in die geschmolzene Kuvertüre tauchen und kalt werden lassen.

---

Quelle: https://www.chefkoch.de/rezepte/269031103557150/Nussecken-a-la-Tanja.html
