= Vegane Amerikaner

* Zubereitung: ca. 15 Minuten
* Backen: ca. 20 Minuten
* Für ca. 12 Stück

== Zutaten

* 100 g vegane Margarine
* 100 g Zucker
* 3 TL Vanillezucker
* 1 zerdrückte Banane
* 300 g Mehl
* 1 Pck. Puddingpulver Vanille
* 100 ml Wasser
* 3 TL Backpulver

== Zubereitung

- Margarine cremig rühren und Zucker und Vanillezucker unterrühren.
Anschließend die zerdrückte Banane hinzufügen und ebenfalls unterrühren.
Mehl, Puddingpulver und Backpulver mischen und abwechselnd mit dem
Wasser in den Teig einrühren.
- Alles gut verkneten und den Teig mit Hilfe von zwei Esslöffeln
portionsweise auf zwei mit Backpapier ausgelegte Backbleche geben, dabei
etwas Abstand zwischen den Amerikanern lassen, da diese beim Backen noch
aufgehen. Bei Bedarf kann man die Teighaufen mit Hilfe eines Messers
noch etwas runder machen.
- Anschließend die Bleche in den vorgeheizten Backofen schieben und bei
180° (oder 160° Umluft) ca. 20 Minuten backen. Nach dem Auskühlen kann
man die flachen Seiten der Amerikaner beliebig mit Zuckerguss oder
Schokoglasur verzieren.
