= Wok-Gemüse

* Zubereitung: ca. 30 Minuten
* Für 2 Personen
* Als Beilage: Basmatireis

== Zutaten

* 1 Kohlrabi
* 1 rote Paprikaschote
* 1 Brokkoli (ca. 300 g)
* 1 rote Zwiebel
* 2 Knoblauchzehen
* 1 Stück Ingwer (ca. 2 cm)
* 1 rote Chili-Schote (nach Belieben)
* 2 EL Öl
* 100 g Maiskörner (frisch abgelöst oder aus dem Glas)
* 3 EL Sojasauce
* 1 EL süße Sojasauce (Ketjap manis)
* 1 EL Limetten- oder Zitronensaft
* 50 ml Gemüsebrühe
* 1 TL Sesamöl
* Salz, schwarzer Pfeffer
* 1 EL Korianderblättchen

== Zubereitung

* Den Kohlrabi schälen und alle holzigen Stellen abschneiden. Kohlrabi
erst in ca. 0,5 cm dicke Scheiben, dann in ebenso breite Streifen
schneiden. Die Paprikaschote waschen, putzen und in Streifen schneiden.
Den Brokkoli waschen und die Röschen abschneiden. Die Stiele schälen und
ebenfalls in Streifen schneiden.
* Die Zwiebel schälen und halbieren, dann in schmale Streifen schneiden.
Den Knoblauch und den Ingwer schälen und in dünne Scheiben schneiden.
Die Chili-Schote, falls verwendet, waschen und mit oder ohne Kerne in
Ringe schneiden.
* Den Wok erhitzen und das Öl hineingießen. Kohlrabi und Brokkoli im Öl
unter Rühren bei mittlerer Hitze 4-5 Minuten braten. Das übrige Gemüse,
Zwiebel, Knoblauch, Ingwer und Chili dazugeben und das Ganze weitere 4-5
Minuten braten bis das Gemüse bissfest ist.
* Die Sojasaucen mit dem Limettensaft, mit Brühe und Sesamöl mischen und
zum Gemüse rühren. Mit Salz und Pfeffer abschmecken und vor dem
Servieren nach Belieben mit Koriander bestreuen.
