repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch # main and master is protected per default, if no args are specified
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
