= Kalter Hund

* Zubereitung: ca. 30 Minuten
* Kühlzeit: ca. 5 Stunden

== Zutaten

* 150 g Kuvertüre, Zartbitter
* 450 g Kuvertüre, Vollmilch
* 150 g Kokosfett
* 200 g Schlagsahne
* 2 Pck. Vanillinzucker
* 250 g	Vollkornbutterkekse

== Zubereitung

* Eine Kastenform mit einem aufgeschnittenen Gefrierbeutel auslegen. Für die
Schokoladencreme beide Kuvertüren grob hacken, das Kokosfett klein schneiden,
alles zusammen mit der Sahne in einem Topf schmelzen und gut verrühren. Zuletzt
Vanillinzucker unterrühren.

* Die Kastenform mit einer Schicht Butterkeksen auslegen, die Kekse eventuell
zerbrechen. Nun so viel Schokoladencreme auf der Keksschicht verteilen, dass
diese bedeckt ist. Abwechselnd Schokoladencreme und Kekse in die Kastenform
schichten (7 - 8 Schichten).

* Die Kastenform etwa 5 Stunden in den Kühlschrank stellen (am besten über
Nacht), damit die Creme fest wird. Das Gebäck mit einem Messer und mithilfe des
Gefrierbeutels aus der Form lösen und vorsichtig auf eine Platte stürzen. Den
Gefrierbeutel vorsichtig abziehen und das Gebäck am besten gekühlt und in
Scheiben geschnitten servieren.

---

Quelle:
https://www.chefkoch.de/rezepte/1139681220190047/Kalter-Hund.html
