= Kinder-Tiramisu

* Zubereitung: ca. 30 Minuten
* Ruhezeit: ca. 3 Stunden
* Für 12 Portionen

== Zutaten

- 40 Löffelbiskuits

### Zum Tränken

- 350 ml Milch
- 55 g Kakaopulver

### Für die Creme

- 500 g Mascarpone
- 600 ml Sahne
- 1 Pck. Vanillezucker
- 1 EL Sahnefest
- 50 g Zucker
- 60 ml Milch

### Zum Bestäuben

- 3 EL Backkakao

== Zubereitung

- Die Schlagsahne aufschlagen. Damit die Masse etwas stabiler wird, das
Sahnefest hinzufügen. Die Mascarpone mit Zucker, Milch und Vanillezucker
cremig rühren. Anschließend die Sahne unter die Creme heben.

- Milch mit dem Kakaopulver mischen. Die Löffelbiskuits darin tauchen und anschließend eine Schicht davon in eine Auflaufform mit den Maßen 30 x 25 cm legen. Auf dieser Schicht ca. die Hälfte der Creme verteilen und diese mit ungesüßtem Backkakao bestäuben. Darauf wieder eine Schicht getränkter Löffelbiskuits geben, dann wieder Mascarponecreme und als letztes den Backkakao.

- Das Tiramisu ca. drei Stunden im Kühlschrank durchziehen lassen.

---

Quelle:
https://www.chefkoch.de/rezepte/3357271499163560/Kinder-Tiramisu.html
