= Tiramisu Alkoholfrei

* Zubereitung: ca. 30 Minuten
* Für 4 Personen

== Zutaten

* 500 g
* Mascarpone
* 2 Becher süße Sahne
* 2 EL Zucker
* 1 Pck. Löffelbiskuits
* 2 Tassen Espresso
* 1 Beutel Amarettini
* 4 EL Kakaopulver, mind. 50 % Kakaoanteil

== Zubereitung

* Den Mascarpone mit Zucker und einem Becher Sahne glatt rühren, die restliche
Sahne steif schlagen und unterheben. Den Espresso abkühlen lassen.
* Die Löffelbiskuits in eine flache Auflaufform legenn und mit Espresso tränken,
jedoch nicht zu nass. Satt mit Kakao und mit zerbröselten Amarettini bestreuen.
Ca. die Hälfte der Mascarponemasse darauf verteilen, je nach Durchmesser der
Schale.
* Erneut Löffelbiskuits auflegen, mit Espresso tränken, den Kakao, die
Amarettinibrösel und den Rest der Mascarponemasse darüber geben, darüber dann
erneut satt Kakao streuen und zum Schluss die zerbröselte Amarettini darüber
streuen.
* Das Tiramisu ca. 2 - 3 Stunden kühl stehen, dann servieren.

---

Quelle: https://www.chefkoch.de/rezepte/605731160381776/Tiramisu.html
