= Fitness-Sandwich

- Zubereitung 20 Minuten
- Für 8 Portionen

== Zutaten

- 125 g Rucola
- 4 Tomaten
- 60 g Pinienkerne
- 3 EL Balsamico
- 5 EL Olivenöl
- 1 EL Honig
- evtl. Salz und Pfeffer
- 200 g Frischkäse (evtl. Kräuterfrischkäse oder italienische Art)
- 100 g Parmesan, frisch gehobelt
- etwas Basilikum
- 1 großes Baguettes

== Zubereitung

- Den Rucola waschen und trockenschütteln, dicke Blattstiele entfernen. Das
Dressing für den Rucola aus Essig, Öl, Honig, Salz und Pfeffer anrühren. Die
Tomaten waschen und in dünne Scheiben schneiden.

- Die Pinienkerne in einer Pfanne ohne Fett knusprig anrösten. Das Baguette
aufschneiden und oben und unten mit dem Frischkäse bestreichen. Den Rucola mit
dem Dressing mischen und auf der unteren Brotseite verteilen. Die
Tomatenscheiben darüber geben und mit Pinienkernen, Parmesanspänen und etwas
zerhacktem Basilikum bestreuen.

- In acht gleich große Stücke zerteilen und servieren.

Quelle: https://www.chefkoch.de/rezepte/1219971227448007/Fitness-Sandwich.html