= Cheese-Burger Pasta

- Zubereitungszeit 25 Minuten
- Für 3 Personen

== Zutaten

- 300 g kurze Pasta
- 1 große rote Zwiebel
- 1 Knoblauchzehe
- 400 g Hackfleisch vom Rind
- 1 TL Knoblauchpulver
- 1 TL Paprikapulver
- 1/2 TL Cayennepfeffer
- 2 EL Ketchup
- 2 EL Mayo
- 2 EL Senf
- 400 g Dose ganze Tomaten in Saft
- 140 g reifer Cheddar in Scheiben
- 3 EL Burger-Gurken
- 2 EL Crème fraîche (optionales Topping)
- 1 Handvoll Frühlingszwiebelgrün (optionales Topping)
- 1/2 Tomate, gewürfelt (optionales Topping)
- Salz und Pfeffer
- Olivenöl

== Zubereitung

- Zwiebel schälen und ca. 1/4 davon fein würfeln und beiseite stellen, den Rest grob würfeln. Knoblauch schälen und fein würfeln.

- Grobe Zwiebelwürfel und Knoblauch in einer Pfanne in etwas Olivenöl mit einer Prise Salz unter gelegentlichem Rühren ca. 2 - 3 Minuten auf mittlerer Hitze andünsten.

- In der Zwischenzeit die Pasta nach Packungsanweisung kochen.

- Bei der Pfanne die Hitze hochdrehen und das Hackfleisch dazugeben. Unter gelegentlichem Rühren einige Minuten scharf anbraten bis es gut gebräunt ist. Dann die Gewürze sowie Salz & Pfeffer dazugeben, gut umrühren.

- Ketchup, Mayo und Senf in die Pfanne geben und gut unterheben. Die Dosentomaten in die Pfanne geben und vorsichtig zerdrücken. Alles kurz köcheln lassen auf kleiner Hitze. Mit Salz und Pfeffer abschmecken.

- In der Zwischenzeit die Gurkenscheiben in Streifen schneiden und die Hälfte der Käsescheiben klein würfeln.

- Gewürfelte Käsescheiben in die Pfanne geben und darin schmelzen. Dann die fertige, abgegossene Pasta mit in die Pfanne geben und unterheben.

- Nun die restlichen Käsescheiben in größeren Stücken oben auf die Pasta legen, Deckel auf die Pfanne legen, Temperatur hochdrehen und den Käse so oben drauf schmelzen lassen für einige Minuten.

- Pasta-Pfanne mit Gurkenstreifen und den fein gewürfelten Zwiebeln sowie optional mit 2 kleinen Esslöffeln Crème fraîche, mit Frühlingszwiebelgrün und fein gewürfelter Tomate bestreut servieren.

Quelle: https://stilettosandsprouts.de/schnelle-cheeseburger-pasta/