= Enchilada-Lasagne

- Zubereitung 30 Minuten
- Backzeitzeit 45 Minuten
- Für 4 Personen

== Zutaten

- 350 g Hackfleisch, gemischt
- 1 Zwiebel, rote
- 2 Knoblauchzehen
- 1 Paprikaschote
- 1 Dose Kidneybohnen, 400 g
- 1 Dose Mais, 300 g
- 1 Dose Tomaten, stückige, 400 g
- 300 g Naturjoghurt
- 150 g Frischkäse mit Paprika
- Paprikapulver, edelsüßes
- Paprikapulver, rosenscharfes
- Salz und Pfeffer
- Tabasco
- Chilipulver
- 1 Pck. Tortilla-Wraps, Durchmesser 20 cm
- 1 Pck. Käse, geriebener, 200 g
- Öl zum Anbraten
- Fett für die Form

== Zubereitung

- Zwiebel und Knoblauch fein hacken und in etwas Öl kurz anbraten. Hackfleisch
hinzufügen, gut anbraten. Mais und Kidneybohnen abtropfen lassen. Klein gehackte
Paprika, den Mais und die Kidneybohnen zugeben und kurz mitbraten. Die gehackten
Tomaten, den Joghurt und den Frischkäse zufügen, gut verrühren und aufkochen.
Ca. 10 - 15 Min. köcheln lassen. Abschmecken, nach Wunsch mit Salz, Pfeffer,
Chili und Tabasco nachwürzen.

- In der Zwischenzeit eine Auflaufform einfetten. Dann beginnen mit etwas Soße,
2 Tortillas nebeneinander legen (liegen ein bisschen übereinander, je nach
Auflaufformgröße), Soße, Tortillas, mit Soße enden. Den geriebenen Käse
darüberstreuen und im vorgeheizten Backofen bei 175 °C Ober-/Unterhitze ca. 20
Min. überbacken, je nach Wunsch, wie braun der Käse werden soll.

Quelle: https://www.chefkoch.de/rezepte/1958641318570605/Mells-mexikanische-Enchilada-Lasagne.html
