= Hirtenpfannkuchen

- Arbeitszeit 15 Minuten
- Ruhezeit 15 Minuten
- Backzeit 25 Minuten
- Für 3 Personen

== Zutaten

- 5 Eier
- 125 g Mehl
- 125 ml Milch
- Salz und Pfeffer
- Muskat
- 125 ml Mineralwasser
- 2 Zwiebeln
- 3 Zehen Knoblauch
- 300 g Blattspinat, frisch oder TK
- 1 EL Öl
- 3 Tomaten
- 200 g Feta-Käse
- evtl. Chili

== Zubereitung

- Eier, Mehl und Milch zu einem glatten Teig verrühren und mit Salz und Pfeffer
kräftig würzen. Ca. 15 Minuten quellen lassen. Den Backofen auf 180°C (Umluft, Gas:
Stufe 2) vorheizen.

- In der Zwischenzeit die Zwiebeln fein würfeln und den Knoblauch hacken. Das Öl
in einer Pfanne erhitzen und die Zwiebel mit dem Knoblauch glasig anschwitzen.
Den Spinat gut abtropfen lassen (TK-Spinat am besten noch etwas auspressen) und
in der Pfanne mitbraten, bis er etwas zusammengefallen ist. Mit Salz, Pfeffer
und Muskat würzen.

- Die Tomaten und den Feta-Käse würfeln. Das Mineralwasser in den Teig
einrühren.

- Die Fettpfanne des Backofens mit Backpapier auslegen und den Teig gleichmäßig
einfüllen. Mit Tomaten, Spinat und Käse belegen. Nach Belieben noch würzen. In
den Backofen schieben und ca. 20 - 25 Minuten backen, bis der Rand braun ist.


Quelle: https://www.chefkoch.de/rezepte/2453991386439740/Hirtenpfannkuchen.html
