= Kartoffelsuppe mit Gemüseeinlage

- Vorbereitung: ca. 20 Minuten
- Zubereitung: ca. 30 Minuten
- Für 4 Portionen

== Zutaten

[cols="1,1", frame="none", grid="none"]
|===

| 1 Karotte, groß
| 400 g Kartoffeln

| 200 g Sellerie
| 1 Paprikaschote

| 150 g Lauchzwiebeln
| 750 ml Wasser

| 1	Zwiebel
| 20 g	Butter

| 1	Gemüsebrühwürfel
| 100 g	Crème fraîche

| Cayennepfeffer
| Muskatnuss

| Kreuzkümmel
|

|===

== Zubereitung

- Die Karotte, 100 g Kartoffeln und den Sellerie schälen. Anschließend alle drei
Zutaten und die Paprikaschote in kleine Würfel schneiden. Von den Lauchzwiebeln
die grüne Seite in feine Ringe schneiden.

- Das Wasser mit etwas Salz erhitzen und darin das Gemüse bis zur gewünschten
Bissfestigkeit garen. Das Gemüse abgießen und dabei das Kochwasser auffangen.

- Die Zwiebel und den weißen Teil der Lauchzwiebeln fein schneiden. Anschließend
im Topf die Butter schmelzen und darin die Zwiebeln glasig dünsten.

- Währenddessen die restlichen Kartoffeln schälen und in Stückchen schneiden.
Zusammen mit dem aufgefangenen Kochwasser und der Gemüsebrühe zu den Zwiebeln
geben. Bei geschlossenem Deckel so lange kochen, bis die Kartoffeln gar sind.

- Die Crème fraîche und die Gewürze hinzugeben. Pürieren, bis keine Stückchen
mehr vorhanden sind. Anschließend nochmal abschmecken.

- Zum Schluss mit den gegarten Gemüsewürfeln und ein paar Kräutern servieren.

---

Quelle: https://www.chefkoch.de/rezepte/3216831478679797/Kartoffelsuppe-mit-Gemueseeinlage.html
