= Rote Thai-Curry Gemüsesuppe


* Für 4 Portionen
* Zubereitung: 10 Minuten
* Kochen: 15 Minuten

== Zutaten

- 2 EL Sesamöl
- 1 Zwiebel
- 2	Paprikaschoten, rote und gelb
- 3	Frühlingszwiebeln
- 2	Möhren
- 200 g	Zuckerschoten
- 1 Glas Champignons, kleine oder frische Champignons
- 4 EL Thai-Currypaste, rot
- 800 ml Kokosmilch
- 150 ml Gemüsebrühe
- 3 EL Sojasauce

== Zubereitung

- Das frische Gemüse waschen. Möhren schälen und in schräge Scheiben schneiden.
Paprikaschoten und Zwiebel in Scheiben schneiden. Frühlingszwiebeln in feine
Ringe schneiden. Die Mini-Champignons abtropfen lassen.

- Das Öl in eine hohe Pfanne oder in einen mittelgroßen Topf geben und die
Zwiebeln darin anschwitzen. Dann die Currypaste dazu geben und 10 Sekunden unter
Rühren mitbraten, mit der Kokosmilch ablöschen. Dann noch die Gemüsebrühe
hinzugeben und 5 Minuten köcheln lassen. Dann das restliche Gemüse mit
hineingeben und weitere 8 Minuten köcheln lassen. Zum Schluss mit Sojasauce Salz
und Pfeffer abschmecken.

---

Quelle: https://www.chefkoch.de/rezepte/3789841578339403/Rote-Thai-Curry-Gemuesesuppe.html
