= Cremige Tomatensuppe mit frittiertem Basilikum

* Vorbereitungszeit: 15 Minuten
* Zubereitungszeit: 35 Minuten
* Für 4 Personen
* Pro Portion ca. 480 kCal

== Zutaten

* 1 kleine Zwiebel
* 1 Knoblauchzehe
* 1/2 Bund Suppengrün
* 2 EL Olivenöl
* 1 Dose Tomatenmark (140 g)
* 1 Dose geschälte Tomaten (400 g)
* 3 Stiele Basilikum und etwas Basilikum zum Garnieren
* 1 Lorbeerblatt
* 200 g Sahne
* 100 ml Pflanzenöl

== Zubereitung

- Zwiebel und Knoblauch abziehen, beide klein schneiden. Suppengemüse
putzen, falls nötig schälen. Gemüse, Zwiebel und Knoblauch in Olivenöl
anbraten. Tomatenmark und Dosentomaten, Basilikum und Lorbeer, Sahne und
500 ml Wasser dazugeben. Alles etwa 20 Minuten kochen lassen.
- Suppe mit Salz und Pfeffer abschmecken, Basilikum und Lorbeer
herausnehmen, Suppe pürieren und nach Belieben durch ein Sieb passieren.
Suppe erneut aufkochen und mit Salz, Pfeffer und Zucker abschmecken.
- Pflanzenöl in einem kleinen Topf erhitzen, einige Basilikumblättchen
darin kurz frittieren. Frittiertes Basilikum herausheben, auf
Küchenpapier abtropfen lassen, mit Salz würzen. Suppe in Gläser oder
Tassen füllen und mit Basilikum garniert servieren.
