= Chinesische Bratnudeln

* Zubereitung: ca. 25 Minuten
* Für 4 Personen

== Zutaten

[cols="1,1", frame="none", grid="none"]
|===

| 250 g Mie-Nudeln, Hsin-Fu
| 4 EL Öl

| 2 Eier
| 2 Zwiebeln

| 2 Knoblauchzehen
| 750 g Gemüsemischung asiatische, TK

| 1 Schuss Sojasauce
| 2 EL Sesamöl

|===


== Zubereitung

- Zwiebeln in halbe Ringe schneiden. Knoblauch in feine Stücke schneiden oder pressen. Herdplatte des Woks auf Stufe 5 von 6 stellen.

- Zuerst die Mie-Nudeln nach Packungsangabe in genügend Wasser garen. Mit kaltem Wasser abschrecken und anschließend mit dem Sesamöl mischen.

- Die Eier verquirlen und in einem Wok mit 1 EL Öl bröselig anbraten, danach beiseitestellen.

- In dem Wok nun mit den restlichen 3 EL Öl das TK-Gemüse nach Packungsangabe garen. Sobald das Gemüse weich wird, Zwiebeln, Knoblauch und einen großen Schuss Sojasauce dazugeben. Nach der angegebenen Zeit mit Salz und Pfeffer würzen, Eier und Nudel dazugeben, mit genügend Sojasauce gut mischen und nochmals 3 Minuten braten.

---

Quelle: https://www.chefkoch.de/rezepte/3414031508693877/Chinesische-Bratnudeln.html

