= Fächerkartoffeln mit Quark

- Zubereitung: ca. 15 Minuten
- Backen: ca. 50 Minuten
- Für 4 Personen

== Zutaten

- 800 g	Kartoffeln, mittelgroße mit zarter Schale
- 200 g	Butter
- 3 Knoblauchzehen, frisch gepresst
- 1 EL Rosmarin, gehackt
- 1 TL Meersalz
- 1 Msp. Kreuzkümmel, gemahlen
- 1/2 TL Cayennepfeffer
- 1 Becher Quark
- 1/2 Bund Petersilie, glatte, mit Stängeln mittelfein gehackt
- 1/2 Bund Schnittlauch, frisch, in feine Röllchen geschnitten
- 1 kleine	Schalotten, in feine Würfel geschnitten
- 3 EL Sahne

== Zubereitung

- Die Kartoffeln ausgiebig waschen und ausprobieren, auf welcher Seite sie am
"stabilsten" liegen. Von oben ca. alle drei Millimeter bis fast "ganz durch" mit
einem scharfen und feinen Messer einschneiden. Die Kartoffeln auf ein Backblech
mit Backpapier legen.

- Die Butter im Topf bei schwacher Hitze schmelzen. In die Butter Knoblauch,
Rosmarin, Meersalz, Kreuzkümmel und Cayennepfeffer rühren. Leicht warm und
flüssig halten und 5 Minuten durchziehen lassen.

- Den Backofen auf 210 Grad (möglichst Umluft) vorheizen.

- Die Hälfte der Butter mit einem Backpinsel über die Kartoffeln
geben. Das Blech mit den Kartoffeln auf der mittleren Position in den
vorgeheizten Backofen schieben. Nach 25 Minuten mit der restlichen
Buttermarinade bepinseln.

- In der Zwischenzeit den Quark mit der Sahne, den Kräutern gemäß Zutatenliste
und der Schalotte verrühren und mit Salz und Pfeffer abschmecken.

- Die Kartoffeln auf Tellern anrichten und mit ein wenig grobem Meersalz
überstreuen. Auf jeden Teller ein Klacks vom Kräuterquark geben.


Quelle:

https://www.chefkoch.de/rezepte/2139701343834129/Catharinas-Ofenkartoffeln-nach-Fiefhusener-Art-mit-Kraeuterquark.html
