= Fladenbrot-Pizza Caprese

- Zubereitung: ca. 20 Minuten
- Backen: ca. 20 Minuten
- Für 4 Personen

== Zutaten

- 1 Fladenbrot
- 3 Tomaten, in dünne Scheiben geschnitten
- 1 Bund Frühlingszwiebeln, in dünne Ringe geschnitten
- 2 Kugeln Mozzarella, grob gewürfelt
- 2 Knoblauchzehen, fein gehackt
- Olivenöl
- Kräuter der Provence
- Basilikum, frisch
- Balsamicocreme

== Zubereitung

- Das Fladenbrot quer halbieren. Beide Hälften auf Backbleche legen, und
mit Olivenöl beträufeln. Mit Knoblauch und Kräutern der Provence
bestreuen. Mit den Tomatenscheiben belegen und mit Salz und Pfeffer
würzen.
- Die Frühlingszwiebeln und zuletzt den Mozzarella auf den Broten
verteilen und nochmal leicht mit Salz und Pfeffer bestreuen. Wieder mit
etwas Olivenöl beträufeln.
- Im heißen Backofen bei 200° Celsius ca. 15 - 20 Minuten überbacken,
bis der Mozzarella schön zerlaufen ist. Mit Basilikumblättchen bestreuen
und etwas Crema di Balsamico darüber träufeln. Die Fladenbrotpizza
Caprese in "Tortenstücke" zerteilen und servieren.

Quelle:
https://www.chefkoch.de/rezepte/1522971257504255/Fladenbrotpizza-Caprese.html
