= Frühlingsrollen mit Sprossen

* Zubereitung: ca. 30 Minuten
* Für 2 Personen

== Zutaten

* 80 g Mungobohnensprossen
* 1 große Möhre
* 2 Frühlingszwiebeln
* 1 Stück frischer Ingwer (ca. 1cm)
* 1 EL Öl
* 1 TL rote Currypaste
* 1 TL Honig
* 6 runde Reispapierblätter (22 cm Durchmesser)
* 1 EL Mehl
* 3 EL dunkle Sojasoße

== Zubereitung

- Die Sprossen verlesen, waschen und gut abtropfen lassen. Die Möhre
waschen, schälen und in feine Streifen schneiden. Frühlingszwiebeln
waschen und putzen, hellen Teil in Streifen, grünen Teil in Ringe
schneiden. Ingwer schälen und fein hacken.
- Zuerst den Wok, dann das Öl darin erhitzen. Sprossen und Möhren
zugeben, unter Rühren 3 Minuten braten. Frühlingszwiebeln und Ingwer
hinzufügen, 1 Minute mitbraten, dabei rühren. Das Gemüse mit Currypaste,
Honig und Salz würzen, herausnehmen und abkühlen lassen.
- Reispapierblätter einzeln in warmes Wasser tauchen, dabei weich werden
lassen. Dann nebeneinander auf ein feuchtes Küchentuch legen. Das Mehl
mit 1 EL Wasser zu einer Paste verrühren.
- Jeweils 3 EL Gemüsefüllung auf die einzelnen Reispapierblätter geben.
Die Seiten einschlagen, dann fest aufrollen. Enden mit etwas Mehlpaste
verschließen. Röllchen in einen Dämpfkorb legen. 5 cm hoch Wasser in den
Wok füllen und bei starker Hitze zum Kochen bringen. Die Rollen
zugedeckt im Wok 10 Minuten dämpfen. Mit Sojasauce servieren.
