= Gebackene Gemüse-Reis-Pfanne

* Vorbereitungszeit: ca. 25 Minuten
* Zubereitungszeit: ca. 30 Minuten
* Für 4 Portionen

== Zutaten

* 1 Zwiebel
* 2 Knoblauchzehen
* 5-6 EL Olivenöl
* 1 TL Paprikapulver
* 400 g passierte Tomaten
* 1 EL getrockneter Oregano
* 1 TL getrockneter Thymian
* 400 ml Gemüsebrühe
* 1 Paprika, rot
* 1 Paprika, gelb
* 2 kleine Zucchini
* 1/2 Aubergine
* 250 g Risotto-Reis
* 10 Kirschtomaten

== Zubereitung

- Zwiebel und Knoblauch abziehen, beides fein würfeln. 2 EL Öl erhitzen,
Zwiebel und Knoblauch darin glasig dünsten. Mit Paprikapulver bestäuben,
passierte Tomaten, Kräuter und Brühe hinzufügen. Die Tomatensauce bei
kleiner Hitze 10 bis 12 Minuten köcheln lassen.
- Den Backofen auf 200° Celsius (Umluft 180° Celsius) vorheizen. Die
Paprika halbieren, putzen, abbrausen. Zucchini und Aubergine waschen,
putzen. Alle Gemüse würfeln.
- In einer großen, ofenfesten Pfanne 2 EL Olivenöl erhitzen, Gemüse
darin 2 bis 3 Minuten anbraten. Reis und die Tomatensauce zum Gemüse
geben, alles mit Salz und Pfeffer würzen.
- Die Pfanne in den Ofen schieben. Den Gemüse-Reis-Mix circa 25 bis 30
Minuten backen. Inzwischen die Kirschtomaten waschen und halbieren. Nach
15 Minuten mit der Schnittfläche nach oben in die Reismischung setzen.
Mit dem übrigen Öl beträufeln und mit Salz und Pfeffern würzen, fertig
garen.
