= Gefüllte Paprika mit Tomatenrahmsosse

* Zubereitung: ca. 25 Minuten
* Kochen: ca. 55 Minuten
* Für 4 Portionen

== Zutaten

- 4 große Paprikaschoten
- 4 Tomaten
- 3	Knoblauchzehen
- 3 EL Rahm
- 200 g	Reis
- 200 ml Gemüsebrühe
- 200 g	Käse, geraspelt
- 1 große Zwiebel
- 1 Bund Kräuter (Petersilie, Basilikum, ...)

=== Für die Sauce

- 2 EL Tomatenmark
- 100 ml Sahne oder Cremefine
- 1 Dose Tomaten, stückige, ca. 400 g
- 1	Zwiebeln

== Zubereitung

- Die Paprikaschoten halbieren und den Strunk, zusammen mit den Kernen,
entfernen. Tomaten vierteln, dann entkernen und klein schneiden.

- Den klein geschnittenen Knoblauch und Zwiebel in etwas Öl anbraten, den Reis
kurz dazugeben. Anschließend mit der Brühe ablöschen und ca. 10 Minuten kochen,
bis der Reis gar aber bissfest ist. Klein gehackte Kräuter, Tomaten und den Rahm
zugeben und nochmals verrühren. Mit Salz, Pfeffer, Zucker abschmecken. Die Masse
in die halbierten Schoten füllen und mit Käse bestreuen.

- Für die Soße Zwiebel klein schneiden und anbraten. Tomatenmark, Tomatenstückchen
und Sahne zugeben. Mit Salz, Pfeffer und Zucker abschmecken.

- Die Schoten bei ca. 180 Grad Umluft ca. 35 Minuten backen. Falls der Käse zu
braun wird, gegen Ende der Garzeit die Schoten mit Alufolie abdecken.

---

Quelle: https://www.chefkoch.de/rezepte/1075441213256912/1A-gefuellte-Paprikaschoten-mit-Tomatenrahmsosse.html
