= Kartoffel-Tortilla

* Vorbereitung: ca. 20 Minuten
* Zubereitung: ca. 30 Minuten
* Für 4 Portionen

== Zutaten

* 750 g Kartoffeln
* 1 Zwiebel
* 1 Knoblauchzehe
* 2 EL Olivenöl
* 30 g getrocknete Tomaten (in Öl)
* 60 g grüne Oliven (entsteint)
* 8 Eier
* Cayenepfeffer
* Salz

== Zubereitung

- Die Kartoffeln schälen, waschen, trocken tupfen und in dünne Scheiben
schneiden. Die Zwiebel und Knoblauchzehe abziehen und in feine Ringe
schneiden bzw. hacken.
- Öl in einer großen, ofenfesten Pfanne erhitzen. Die Kartoffeln und die
Zwiebel darin bei mittlerer Hitze unter gelegentlichem Wenden ca. 15
Minuten braten. Den Backofen auf 200° Celsius (Umluft 180° Celsius)
vorheizen.
- Inzwischen die Tomaten abtropfen lassen und fein hacken. Die Oliven
abbrausen, trocken tupfen und in Ringe schneiden. Tomaten, Oliven und
Knoblauch zu den Kartoffeln geben und kurz mitbraten.
- Eier aufschlagen, in einer großen Schüssel verquirlen, mit Salz und
Cayenepfeffer kräftig würzen. Zu den Kartoffeln in die Pfanne gießen,
kurz anbraten. Tortilla im Ofen in 15 bis 20 Minuten stocken lassen.
Tortilla aus der Pfanne auf ein Brett gleiten lasen, in Stücke schneiden
und servieren.
