= Tortellini in fruchtiger Tomatensahnesauce

* Zubereitung: ca. 20 Minuten
* Backzeit: ca. 10 Minuten
* Für 3 Personen

== Zutaten

- 850 g	Tomate(n), geschälte
- Kräuter wie Oregano, Thymian, Basilikum
- Salz
- Zucker
- 200 ml Sahne, süß
- 1	Möhre(n)
- 1 kleine Zwiebel(n)
- 2 EL Petersilie
- Olivenöl
- 1 EL Zucker
- 750 g Tortellini
- 50 g Käse, Gouda gerieben, ca.
- 20 g Parmesan, gerieben, ca.
== Zubereitung

- Die Tomaten mit dem Passierstab zerkleinern, die Gewürze hinzufügen und aufkochen. (Thymian nur eine Prise, Oregano und Basilikum etwas mehr und Salz und Zucker jeweils etwa einen halben TL, bitte selbst herantasten).
Süße Sahne zugeben und weiter auf kleiner Flamme köcheln lassen.
- Die Möhre in feine Würfel schneiden, ebenso die Zwiebel, im Olivenöl mit dem Zucker glasig dünsten (etwa 15 Minuten), dann für kurze Zeit die Petersilie mit anschwitzen und alles zur Tomatensahnesauce zugeben.

- Tortellini kochen bis "al dente", eine Auflaufform mit etwas Olivenöl auspinseln und die abgeschütteten Tortellini hineinfüllen. Die Sauce darüber geben und den Käse lose darüber verteilen.

- Bei 175°C backen, bis der Käse schön zerläuft.


---

Quelle: https://www.chefkoch.de/rezepte/1546681261145742/Tortellini-mit-fruchtiger-Tomatensahnesauce-ueberbacken.html
