= Udon Nudeln mit Erdnusssauce & Gemüse

- Zubereitungszeit 15 Minuten
- Für 4 Personen

== Zutaten

- 400 g Udon Nudeln, vorgegart
- 1 Gurke
- 1 kleine Zucchini
- 200 g Zuckerschoten
- 1 orange Paprika
- 5 Lauchzwiebeln
- Kokosöl
- Erdnusssauce
- 4 EL Erdnussbutter
- 2 TL Chilisauce
- 2 EL Fischsauce
- 2 TL Ahornsirup
- 2 TL Sojasauce, chinesisch
- 165 ml Kokosmilch (kleine Dose)
- 2 EL Reisessig
- 1 Limette


== Zubereitung

- Zuckerschoten, Paprika und Zucchini in dünne Streifen schneiden. Von der Gurke das wässrige Innere entfernen und den Rest in dünne Streifen schneiden. Von den Frühlingszwiebeln den grünen Teil in dünne Ringe schneiden.

- Die Udon Nudeln nach Packungsanweisung in kochendem Wasser kochen. (2 Min.) Danach abschütten und kurz mit kaltem Wasser abspülen.

- In der Zwischenzeit Zucchini in Kokosöl auf mittlerer Hitze ca. 2 Minuten andünsten. Die Zuckerschoten dazugeben und beides 2 weitere Minuten andünsten. Dann beides aus der Pfanne nehmen und mit den Nudeln in eine große Schüssel geben.

- Nun die Erdnusssauce herstellen: Erdnussbutter mit Chilisauce, Fischsauce, Ahornsirup und Sojasauce in einem kleinen Topf auf mittlerer Hitze erhitzen und dabei konstant rühren. Dabei entsteht eine dickere Paste. Den Topf vom Herd nehmen, Kokosmilch einrühren und mit Limettensaft und Reisessig abschmecken.

- Sauce zu den Nudeln geben, Paprika und Gurke dazu geben, alles gut vermengen und mit Frühlingszwiebelgrün bestreut servieren. Guten Appetit.

Quelle: https://stilettosandsprouts.de/udon-nudeln-mit-erdnusssauce/