= Zucchini-Tomaten-Quiche

* Zubereitung: ca. 20 Minuten
* Backen: ca. 40 Minuten
* Für 1 Springform mit 26 cm Durchmesser

== Zutaten

* 1 Zucchini
* 250 g Kirschtomaten
* 250 g Ziegenfrischkäse
* 3 Eier
* 200 g Schlagsahne
* Salz, Pfeffer, Muskat
* 1 Päckchen Blätterteig (Kühlregal)
* 2 EL Semmelbrösel
* 100 g Ziegenweichkäse
* 2 EL Knoblauchöl

== Zubereitung

- Die Zucchini waschen, putzen und längs in dünne Scheiben schneiden.
Die Kirschtomaten waschen und halbieren.
- Den Frischkäse mit Eiern und Sahne verrühren. Kräftig mit Salz,
Pfeffer und Muskat würzen. Den Backofen auf 220° Celsius (Umluft: 200°
Celsius) vorheizen.
- Den Blätterteig in die mit Backpapier ausgelegte Springform legen.
Semmelbrösel aufstreuen. Zucchini und die Hälfte der Tomaten auf den
Teig geben. Ziegenfrischkäsemasse darauf verteilen. Den Ziegenweichkäse
zerbröckeln und zusammen mit den restlichen Tomaten auf der Quiche
verteilen. Die Oberfläche der Tomaten und Zucchini mit Öl bepinseln und
die Quiche im Ofen etwa 30 Minuten backen.
- Temperatur auf 230° Celsius (Umluft: 210° Celsius) erhöhen und die
Quiche weitere 10 Minuten backen.