= Macadamia-Cookies

* Zubereitung: ca. 20 Minuten
* Für ca. 50 Stück

== Zutaten

* 300 g Mehl
* Salz
* 1 gehäufter TL Backpulver
* 250 g weiße Schokolade
* 1 Ei (Größe M)
* 275 g weiche Butter
* Mark von 3 Vanilleschoten
* 175 g Rohrzucker
* 300 g Macadamia-Nüsse (geröstet und gesalzen)
* 50 g Schokoladentröpfchen (Fertigprodukt)

== Zubereitung

- Mehl, 1 Prise Salz und Backpulver in eine Schüssel sieben. Die
Schokolade in ca. 1/2 cm große Stücke hacken. Ei verquirlen.
- Butter und Vanillemark mit den Quirlen des Handrührers 5 bis 8 Minuten
schaumig schlagen. Zucker dazugeben und weitere 4 Minuten schlagen,
dabei zum Schluss das Ei nach und nach hinzufügen.
- Mehlmischung unterrühren, weiße Schokolade und 250 g Macadamia-Nüsse
mit einem Kochlöffel unterziehen, sodass sie gleichmäßig verteilt sind.
- Backbleche mit Backpapier belegen. Mit Hilfe eines Ausstechrings (ca.
4,5 cm Durchmesser) ca. 1 cm hohe, glatte Teighäufchen auf die Bleche
setzen. Dafür einen angefeuchteten Teelöffel verwenden und jeweils 5 cm
Abstand halten. Restliche Macadamia-Nüsse grob hacken, mit den
Schokotropfen auf den Cookies verteilen.
- Die Cookies im vorgeheizten Backofen bei 170° Celsius auf der 2.
Einschubleiste von unten 12 bis 14 Minuten backen. Nach dem Backen noch
kurz auf dem Blech lassen, dann auf Kuchengittern auskühlen lassen.
