= Zitronengras-Vanilla-Cookies

* Zubereitung: ca. 20 Minuten
* Backzeit: ca. 12 Minuten
* Ergibt ca. 25 Stück

== Zutaten

* 100 g Butter
* 1 Ei (Größe M)
* 2 Stangen Zitronengras
* 5 EL Zucker
* 130 g Mehl
* 2 Msp. Backpulver
* 1 Pck. natürliches Bourbon-Vanille-Aroma

== Zubereitung

- Die Butter rechtzeitig aus dem Kühlschrank nehmen und weich werden
lassen. Das Ei ebenfalls aus dem Kühlschrank nehmen und Zimmertemperatur
annehmen lassen. Den Backofen auf 180° Celsius (Umluft: 160° Celsius)
vorheizen. Zwei Backbleche mit Backpapier auslegen. Das Zitronengras
waschen, die unteren Enden und die oberen dünnen Teile abschneiden. Die
mittleren dicken Teile im Blitzhacker oder mit einem großen Messer sehr
fein hacken.
- Die weiche Butter mit dem Zucker in eine Rührschüssel geben und mit
dem Schneebesen des Handrührgeräts glatt rühren. Nun zuerst das Ei
unterrühren, dann das Mehl abmessen und mit dem Backpulver, dem
Zitronengras und dem Bourbon-Vanille-Aroma rasch untermischen.
- Vom Teig mit zwei kleinen Löffeln walnussgroße Haufen abnehmen und mit
etwas Abstand auf die Bleche setzen. Die Bleche nacheinander (bei Umluft
gleichzeitig) in den heißen Ofen (Mitte) schieben und die Cookies in
jeweils 10 bis 12 Minuten goldbraun backen.
