= Bunte Gemüsesuppe mit Buchstabennudeln

* Zubereitung: ca. 25 Minuten
* Kochen: ca. 15 Minuten
* Für 6 (Kinder-) Portionen

== Zutaten

* 120 g Buchstabennudeln
* 200 g Möhren
* 250 g Knollensellerie
* 200 g Lauch
* 250 g Chinakohl
* 200 g grüne Paprika
* 1 EL Rapsöl
* 1 Bund Petersilie
* 1,5 l Gemüsebrühe

== Zubereitung

- Die Nudeln nach Packungsanleitung in kochendem Salzwasser knapp
bissfest kochen.
- Inzwischen Möhren und Sellerie schälen und in 5mm große Würfel
schneiden. Den Lauch putzen, waschen, längs halbieren und in feine Ringe
schneiden. Den Chinakohl ebenfalls putzen, waschen, in einem Sieb
abtropfen lassen und in schmale Streifen schneiden.
- Die Paprikaschote halbieren, die kleinen Samenkerne und die weiße
Innenhaut entfernen. Die Paprikahälften waschen und ebenfalls in schmale
Streifen schneiden.
- Die Nudeln in einem Sieb abgießen, unter fließendem Wasser kalt spülen
und gut abtropfen lassen.
- Das Öl in einem Topf erhitzen. Die Möhren- und Selleriewürfel darin 1
Minute andünsten.
- Paprika- und Chinakohlstreifen zum Gemüse in den Topf geben und
ebenfalls kurz andünsten. Salzen, pfeffern , die Gemüsebrühe hinzugeben
und alles 10 Minuten bei mittlerer Hitze kochen lassen.
- Zuletzt die Lauchringe dazugeben und weitere 4 Minuten garen.
Inzwischen die Petersilie waschen, trockenschütteln, die Blätter
abzupfen und fein hacken. Die Nudeln zur Suppe zugeben und kurz
erhitzen. Die Suppe in eine Terrine geben, mit Petersilie bestreuen und
servieren.