= Kohlrabisuppe mit Kartoffeln


* Zubereitung: ca. 20 Minuten
* Kochen: ca 25 Minuten
* Für 4 Portionen

== Zutaten

- 2 Zwiebeln
- 2 Kohlrabi
- 800 g	Kartoffeln
- 2 EL Öl
- 1 Liter Gemüsebrühe
- 200 ml Sahne
- 2 TL Kräuter, TK
- 1 Bund Petersilie
- Muskat

== Zubereitung

- Die Zwiebeln abziehen, fein hacken. Kohlrabi und Kartoffeln schälen, waschen und
in Würfel schneiden.

- Das Öl in einem Topf erhitzen und die Zwiebeln darin andünsten. Kohlrabi- sowie
Kartoffelwürfel dazugeben und kurz mitdünsten. Brühe angießen und zugedeckt ca.
20 Min. köcheln lassen.

- Einige Esslöffel Gemüse aus der Suppe nehmen und beiseite stellen. Den Rest in
der Brühe pürieren. Sahne und Kräuter hinzufügen, Brühe dabei nicht mehr kochen
lassen. Das übrige Gemüse wieder in die Suppe geben.

- Petersilie abbrausen, trocken schütteln, einige Blätter beiseite legen, den Rest
hacken und unter die Suppe rühren. Mit Muskat, Salz und Pfeffer abschmecken. Die
Suppe anrichten und mit der übrigen Petersilie garniert servieren.

---

Quelle: https://www.chefkoch.de/rezepte/942201199808811/Kohlrabisuppe-mit-Kartoffeln.html
