= Paprika-Kichererbsen-Suppe

* Für 4 Personen
* Zubereitung: ca. 40 Minuten

== Zutaten

* 1 kg Paprikaschoten, rot
* 150 g Kichererbsen, getrocknet
* 1 l Gemüsebrühe
* 3 Zwiebeln
* 2 Zehen Knoblauch
* 1 EL Majoran
* Butter (alternativ Olivenöl)
* etwas Schmand
* 1 Prise Salz
* 3 bis 4 EL Zucker
* Saft einer Zitrone

== Zubereitung

- Am Abend vorher die getrockneten Kichererbsen waschen und über Nacht
in reichlich kaltem Wasser einweichen.
- Die Kichererbsen mit dem Einweichwasser am nächsten Tag aufsetzen und
ca. 60 Minuten kochen.
- In der Zwischenzeit die Paprikaschoten waschen, in Stücke schneiden,
dabei Stiele und Kerngehäuse entfernen und zusammen mit den grob
zerkleinerten Zwiebeln und dem gehackten Knoblauch in einem großen Topf
mit der Butter (oder dem Öl) dünsten und leicht bräunen. Mit der Hälfte
der Gemüsebrühe ablöschen, die inzwischen abgegossenen Kichererbsen
(Wasser zurückbehalten!) bis auf 3 EL dazugeben, alles zusammen im
geschlossenen Topf noch ca. 20 Minuten köcheln lassen und anschließend
pürieren.
- Eventuell die Masse durch ein sehr grobes Sieb streichen (sofern
vorhanden), ansonsten die pürierte Suppe nun mit der restlichen
Gemüsebrühe auffüllen und die zurückbehaltenen Kichererbsen dazugeben.
Nun noch mit Majoran, Salz und Pfeffer abschmecken und alles zusammen
noch einmal kurz aufkochen.
- Je nach Geschmack die Suppe mit etwas Kichererbsenwasser verdünnen.
Zum Schluss mit einem Löffel Schmand auf dem Teller anrichten.