= Rote Zwiebelrahmsuppe

* Für 4 Portionen

== Zutaten

* 500 g rote Zwiebeln
* 150 ml Apfelsaft
* 2 EL Tomatenmark
* 1 l Gemüsebrühe (instant)
* 4 Scheiben Bauernbrot ohne Kruste
* 6 Zweige Majoran (ersatzweise 1 TL getrockneter Majoran)
* 150 g Creme fraiche
* 5 EL Öl

== Zubereitung

- Die Zwiebeln abziehen, halbieren und in feine Streifen schneiden. Die
Zwiebelstreifen in 2 EL Öl bei mittlerer Hitze zugedeckt in 5 Minuten
weich dünsten, dabei leicht salzen. 2 - 3 EL herausnehmen und
beseitestellen. Den Rest mit der Hälfte des Apfelsaftes ablöschen und
diesen ganz einkochen lassen. Den Vorgang mit übrigem Apfelsaft
wiederholen.
- Das Tomatenmark einrühren und kurz anrösten. Gemüsebrühe dazugeben,
mit Salz und Pfeffer würzen. 10 Minuten köcheln lassen.
- Inzwischen das Brot würfeln. Majoranblättchen abzupfen. Das übrige Öl
(3 EL) in einer Pfanne erhitzen, die Brotwürfel in ca. 3 Minuten
goldbraun rösten. Zum Schluss den Majoran und die übrigen Zwiebeln
hinzufügen und kurz miterhitzen.
- Creme fraiche in die Suppe rühren und diese mit dem Mixstab fein
pürieren. Aufkochen, mit Salz, Pfeffer abschmecken und in Tellern oder
Schalen anrichten. Die Suppe mit den Croutons und Zwiebeln garniert
servieren.