= Tomatensuppe mit Reis

- Vorbereitung: ca. 15 Minuten
- Zubereitung: ca. 40 Minuten
- Für 2 Personen

== Zutaten

- 400 g Tomaten, vollreif
- 1 Zwiebel, rot
- 2 EL Olivenöl
- 2 TL Kräuter, gemischte getrocknete
- 60 g Reis
- 600 ml Gemüsebrühe
- 3 TL Tomatenmark
- 1 TL Zucker
- Sambal Oelek
- 1/2 Bund Petersilie
- 1 Handvoll Käse, gerieben

== Zubereitung

- Die Tomaten waschen und in sehr kleine Würfel schneiden. Die Zwiebel schälen und fein schneiden.

- Das Öl im Suppentopf erhitzen, Zwiebel und Kräuter dazugeben und kurz anbraten, bis die Zwiebeln weich werden. Dabei immer rühren. Nun den Reis untermischen und rühren, bis alle Körner vom Öl überzogen sind. Tomaten und Brühe dazugeben und die Suppe zum Kochen bringen.
- Mit Salz, Pfeffer, Zucker, Tomatenmark und Sambal Oelek würzen und die Suppe ca. 30 Minuten köcheln lassen.
- Zum Schluss die Petersilie fein hacken, und gemeinsam mit der Crème fraîche oder Cremefine oder dem geriebenen Käse (nach Geschmack) untermischen und die Suppe nochmal abschmecken.


---

Quelle: https://www.chefkoch.de/rezepte/1679571276063332/Leichte-Tomatensuppe-mit-Reis.html
