= Bienenstich

* Für 1 Backblech (16 Stücke)
* Zubereitungszeit: 60 Minuten
* Ruhen: 55 Minuten
* Backzeit: 30 Minuten

== Zutaten

=== Für den Hefeteig

* 500 g Mehl
* 1 Prise Salz
* 1 Würfel Hefe (42 g)
* 250 ml lauwarme Milch
* 80 g Zucker
* 150 g flüssige Butter
* 1 Ei
* Backpapier fürs Blech
* Mehl für die Arbeitsfläche

=== Für den Belag

* 100 g Butter
* 100 g Zucker
* 1 Päckchen Vanillezucker
* 2 EL flüssiger Honig
* 100 g Sahne
* 200 g gehobelte Mandeln

=== Für die Füllung

* 2 Päckchen Vanillepuddingpulver
* 750 ml Milch
* 80 g Zucker
* 100 g weiche Butter
* 2 EL Puderzucker

== Zubereitung

- Für den Teig Mehl und Salz in eine Schüssel geben, in die Mitte eine
Mulde drücken. Hefe zerbröckeln und in 125 ml lauwarmer Milch glatt
rühren. Die Hefemilch in die Mehlmulde gießen, mit 1 Prise Zucker
bestreuen und zugedeckt an einem warmen Ort 15 Minuten gehen lassen.
Butter mit der restlichen Milch, dem restlichen Zucker und dem Ei zum
Vorteig geben. Den Teig schlagen, bis er sich vom Rand löst. Zugedeckt
30 Minuten gehen lassen.
- Für den Belag Butter, Zucker, Vanillezucker, Honig und Sahne unter
Rühren erhitzen. Mandeln hinzufügen, kurz aufkochen und leicht abkühlen
lassen. Ab und zu umrühren.
- Backblech mit Backpapier auslegen. Backofen auf 200° Celsius
vorheizen. Teig auf bemehlter Arbeitsfläche ausrollen, auf das Blech
geben und 10 Minuten ruhen lassen. Mandelmasse auf den Teig streichen.
Im Ofen (Mitte, 180° Celsius Umluft) 30 Minuten backen lassen.
- Puddingpulver mit 125 ml Milch anrühren. Restliche Milch mit Zucker
aufkochen lassen, Puddingmilch hineinrühren, aufkochen, dann abkühlen
lassen, ab und zu rühren. Butter mit Puderzucker cremig rühren, Pudding
unterrühren. Kühl stellen.
- Den Kuchen in vier Stücke schneiden, diese waagerecht durchschneiden.
Creme aufstreichen. Teigdeckel in je vier Stücke, nebeneinander auf den
Pudding legen. Bienenstich-Stücke ganz durchschneiden.
