= Kirsch-Mandel-Kuchen

* Zubereitung: ca. 60 Minuten + 80 Minuten Ruhezeit
* Backzeit: ca. 30 Minuten
* Für 1 Backblech bzw. 16 Stücke

== Zutaten

=== Für den Teig

* 500 g Mehl und Mehl zum Arbeiten
* 60 g Zucker
* Salz
* 1 Würfel Hefe
* 250 ml lauwarme Milch
* 2 Eier
* 50 g Butter

=== Für den Belag

* 600 g Sauerkirschen (ersatzweise Schattenmorellen aus dem Glas)
* 125 g Butter
* 100 g Zucker
* 150 g Mandelblättchen

== Zubereitung

- Für den Teig das Mehl, den Zucker und eine Prise Salz in eine Schüssel
geben und in das Mehl eine Mulde drücken. Die Hefe zerbröckeln, in 50 ml
Milch anrühren und in die Mulde gießen. Alles zugedeckt ca. 20 Minuten
ruhen lassen. Dann die Eier, die Butter und die übrige Milch hinzufügen,
zu einem glatten Teig verkneten. Zugedeckt an einem warmen Ort 30
Minuten gehen lassen.
- Inzwischen die Kirschen verlesen, waschen und entsteinen. Den Teig
nochmal durchkneten und auf einem mit Backpapier belegten Blech
ausrollen. Den Teig nochmals 30 Minuten gehen lassen. Den Backofen auf
180° Celsius (Umluft: 160° Celsius) vorheizen.
- Mit einem Kochlöffel in gleichmäßigem Abstand Vertiefungen in den Teig
drücken. Butter in Flöckchen in die Mulde geben. Den Teig mit den
Kirschen belegen und diese leicht eindrücken. Den Zucker mit den
Mandelblättchen vermischen und auf die Kirschen streuen. Den Kuchen im
Ofen auf der mittleren Schiene ca. 30 Minuten backen.
