= Philadelphia Torte mit Mandarinen und Löffelbiskuits

- Zubereitung: ca. 30 Minuten
- Ruhezeit: 8 Stunden
- 1 Springform mit 26 cm Durchmesser

== Zutaten

- 80 g Zucker
- 125 g Butter, zerlassen
- 200 g Frischkäse
- 2 kl. Dosen Mandarinen
- 400 g	Löffelbiskuits
- 1/2 Liter Sahne
- 1 Pck. Götterspeise (Zitrone)

== Zubereitung

- Zuerst die Götterspeise mit dem Abtropfsaft der Mandarinen kochen und abkühlen
lassen. Danach den Frischkäse mit Zucker verrühren. Mandarinen mit dem
Frischkäse vermengen und die Götterspeise unterrühren. Dann die Sahne schlagen
und unterheben.

- Für den Rand 15 Biskuits zur Seite legen und halbieren. Für den Boden den Rest
der Biskuits zerbröseln. 3 Esslöffel Biskuitbrösel für den Belag zur Seite
stellen. Für den Boden die restlichen Brösel mit der Butter vermengen.

- Die Bodenmasse in die Kuchenform drücken und die Biskuithälften am Rand
ringsum aufstellen. Die Frischkäsemasse einfüllen und mit den 3 EL Biskuitbrösel
bedecken. Über Nacht im Kühlschrank fest werden lassen.

---

Quelle: https://www.chefkoch.de/rezepte/1024691207642451/Philadelphia-Torte-mit-Mandarinen-und-Loeffelbiskuits.html
