= Amaretto-Sahne-Torte

- Vorbereitung: ca. 15 Minuten
- Backen: ca. 55 Minuten
- Für 1 Springform mit 26 cm Durchmesser
 
== Zutaten

- 1000 g Ricotta
- 200 g Zucker
- 50 g Mehl
- 6 Eier
- 1 Orange
- 150 g Vollkornkekse
- 80 g Butter
- 1 TL Vanilleextrakt
- Puderzucker

== Zubereitung

- Die Kekse zerbröseln (z.B. in einem Gerfrierbeutel und mit dem Nudelholz).
Keksbrösel mit der weichen Butter verkneten und dann in eine am Boden mit
Backpapier ausgelegte Kuchenform geben. Für 30 Minuten kaltstellen.

- Mehl und Zucker in einer Schüssel zusammenfügen und vermischen. - Den Ricotta
in eine weitere Schüssel geben, den Abrieb einer Orange dazugeben und
unterrühren. - Die Mehl-Zucker-Mischung mit einem Backspatel vorsichtig
unterheben und gut vermengen. - Die Eier eins nach dem anderen zu der Masse
geben und jeweils mit dem Backspatel gut unterrühren, sodass am Ende ein
schöner, homogener Teig entsteht. - Vanilleextrakt zufügen und einrühren. - Den
Teig in die Form mit dem gekühlten Keksboden füllen. Form bei 175° Ober- und
Unterhitze im vorgeheizten Backofen auf der unteren Schiene (nicht die ganz
unterste, sondern eine unterhalb der mittleren) ca. 55 - 60 Minuten backen. (Die
Backzeit kann je nach Ofen variieren. Am besten mit einem Zahnstocher die
Stäbchenprobe in der Mitte des Kuchens machen. Wenn die Masse dort nicht mehr
flüssig, sondern fest ist, ist der Kuchen gar.) - Kuchen auf einem Gitter
auskühlen lassen und anschließend für ca. 3 Stunden im Kühlschrank kaltstellen.
- Vor dem Servieren mit Puderzucker und, auf Wunsch, mit Orangenabrieb
bestreuen.

---

Quelle: https://stilettosandsprouts.de/italian-ricotta-cheesecake/