= Zitronenkuchen

* Zubereitung: ca. 70 Minuten
* Backzeit: ca. 50 Minuten

== Zutaten

=== Für den Teig

* 150 g Mehl
* 25 g Zucker
* 125 g Butter
* 1 EL Wasser

=== Für den Belag

* 150 g Creme double
* 100 g Zucker
* Abrieb von 3 Zitronen
* 4 Eier
* 12 EL Zitronensaft
* 1 EL Puderzucker

== Zubereitung

- Das Mehl und den Zucker in eine Schüssel geben. Die Butter mit den
Fingern in der Mischung verreiben. Das Wasser hinzufügen und alles zu
einem weichen Teig verarbeiten. Den Teig für 30 Minuten in den
Kühlschrank stellen.
- Den Teig auf einer mit Mehl bestäubten Arbeitsplatte ausrollen und in
eine Tarte-Form (24 cm Durchmesser) einpassen. Anschließend mit einer
Gabel einstechen und weitere 30 Minuten kaltstellen.
- Den Teig mit Alu-Folie und Backbohnen bedecken und in einem
vorgeheiztem Backofen bei 190° Celsius ca. 15 Minuten blind backen.
Folie und Bohnen entfernen und den Teig weitere 15 Minuten backen.
- Für die Füllung Creme double, Zucker, Zitronenschalen, Eier und Saft
verquirlen. Die fertige Mischung auf dem Teig verteilen und die Form auf
ein Backblech stellen.
- Den so vorbereiteten Kuchen 20 Minuten backen, bis die Füllung stockt.
Anschließend auskühlen lassen und vor dem Servieren mit Puderzucker
bestäuben.
