= Kartoffel-Gurken-Salat

* Zubereitung: ca. 25 Minuten
* Kochzeit: ca. 20 Minuten
* Ruhezeit: 5-6 Stunden
* Für 3 Personen
  
== Zutaten

* 750 g	festkochende Kartoffeln
* 1 mittelgroße	Zwiebel
* 200 ml kräftige Gemüsebrühe
* 1 EL Senf
* 3 EL Weißweinessig
* 1/2 Salatgurke
* 2	Frühlingszwiebeln
* 3 EL Rapsöl
* Petersilie


== Zubereitung

* Die Kartoffeln kochen, pellen und noch warm in Scheiben schneiden.
* Die Zwiebel in kleine Würfel schneiden und mit der heißen Brühe übergießen. Anschließend mit Senf und Essig verrühren und über die Kartoffeln geben. Etwa 2 Stunden ziehen lassen.
* Die Gurke der Länge nach halbieren und mit einem kleinen Löffel das Kerngehäuse auskratzen. In dünne Scheiben schneiden. Die Frühlingszwiebeln halbieren und ebenfalls klein schneiden. Zusammen mit dem Öl unter die Kartoffeln geben und nochmal etwa 1/2 Stunde ziehen lassen. 
* Mit Salz, Pfeffer und Petersilie abschmecken.

---

Quelle: https://www.chefkoch.de/rezepte/2127351342185624/Kartoffel-Gurken-Salat.html