= Tomaten-Brot-Salat

* Für 4 Personen

== Zutaten

* 20 Kirschtomaten
* 1 rote Zwiebel
* 3 Knoblauchzehen
* 1/2 Baguette, ca. 2-3 Tage alt
* 2 Zweige Rosmarin
* 30 g Pinienkerne
* 50 g Parmesan
* 1/2 Chilischote
* Zitronensaft
* Salz
* Pfeffer
* Olivenöl

== Zubereitung

- Die Tomaten halbieren und die Stielansätze entfernen, die Chilischote
mit oder ohne Kerne hacken. Die rote Zwiebel und den Knoblauch schälen
und in feine Lamellen bzw. Scheiben schneiden. Den Parmesankäse in feine
Späne hobeln.
- Das Brot in dünne Scheiben schneiden und ohne Fett in einer Pfanne
knusprig rösten. In einer zweiten Pfanne Olivenöl erhitzen,
Rosmarinnadeln, Pinienkerne, Zwiebeln, Knoblauch und Tomaten hineingeben
und kurz scharf anbraten, dabei die Pfanne immer gut bewegen. Die
Tomaten sollten unbedingt noch Form haben und nicht zu weich werden.
- Alles in eine Schüssel geben, die Brotscheiben und den Parmesankäse
hinzufügen und vermengen. Den Salat mit Salz, Pfeffer, Olivenöl und
Zitronensaft abschmecken.
