= Amaretto-Sahne-Torte

* Zubereitung: ca. 45 Minuten
* Backen: ca. 45 Minuten
* Für 1 Springform mit 26 cm Durchmesser

== Zutaten

* 4 Eier
* 250 g Zucker
* 200 ml Öl
* 200 ml Orangensaft
* 300 g Mehl
* 4 EL Kakaopulver
* 1 Päckchen Backpulver
* 8 EL Mandellikör (z.B. Amaretto)
* 800 g Sahne
* 2 Päckchen Vanillezucker
* 350 g Amaretti
* 1 EL Kakaopulver zum Bestäuben
* Fett für die Form

== Zubereitung

- Den Ofen auf 200° Celsius vorheizen. Die Eier mit Zucker dickcremig
schlagen. Öl und Saft zugeben. Mehl mit Kakao und Backpulver mischen,
rasch unterrühren. Den Teig in die gefettete Form füllen, im Ofen
(unten) ca. 40 bis 45 Minuten backen und abkühlen lassen.
- Den Kuchen einmal quer teilen. Den Boden mit einem Tortenring
umstellen und mit 4 EL Amaretto tränken. Die Sahne mit dem Vanillezucker
steif schlagen und zwei Drittel auf den Boden geben. 12 Amaretti für die
Dekoration aufheben, die restlichen in die Sahne drücken. Den Deckel
auflegen, mehrfach mit einem Holzstäbchen einstechen, mit 4 EL Amaretto
tränken.
- Die restliche Sahne auf die Torte streichen, die Amaretti den Rand
entlang setzen.
- Die Mitte der Torte mit Kakao bestreuen.