= Apfelmus-Kuchen

* Zubereitung: ca. 50 Minuten
* Backzeit: ca. 60 Minuten
* 3 Stunden Kühlzeit

== Zutaten

=== Für den Teig

* 125 g kalte Butter
* 250 g Mehl
* 70 g Zucker
* 1 Ei
* Salz

=== Für den Belag

* 1 kg säuerliche Äpfel (z.B. Boskop)
* 1 Haselnuss-grosses Stück Ingwer
* 2 Gewürznelken
* 2 Zitronenscheiben (Bio)
* 70 g Zucker
* 500 ml Weißwein, halbtrocken
* 2 Pck. Sahnepuddingpulver (für je 500 ml Milch)
* 200 g Schlagsahne
* 1 Pck. Sahnesteif
* 1 EL Puderzucker
* 1 - 2 EL Kakaopulver

== Zubereitung

- Alle Teigzutaten zu einem glatten Teig verkneten. In Folie gewickelt
mindestens 30 Minuten kalt stellen.
- Die Äpfel schälen, das Kerngehäuse entfernen und die Äpfel würfeln.
Den Ingwer schälen und in Scheiben schneiden. Beides mit Nelken,
Zitronenscheiben und Zucker in 400 ml Wein aufkochen. Fünf Minuten
köcheln lassen, vom Herd ziehen. Ingwer, Nelken und Zitronenscheiben
entfernen.
- Puddingpulver mit den übrigen 100 ml Weißwein glatt rühren, zum
Apfel-Mix geben. Aufkochen, vom Herd nehmen. Den Backofen auf 150
° Celsius (Umluft: 130 °Celsius) vorheizen.
- Den Teig auf bemehlter Fläche ausrollen, in die mit Backpapier
ausgelegte Springform geben, einen Rand hochziehen. Die Apfelmasse
einfüllen und im Ofen ca. 60 Minuten backen. Den Kuchen auskühlen lassen
und mindestens drei Stunden kalt stellen.
- Zum Servieren die Sahne mit Sahnesteif und Puderzucker steif schlagen.
Auf den Kuchen streichen. Den Kuchen mit Kakaopulver bestäuben und nach
Belieben mit in Zitronensaft marinierten Apfelscheiben garnieren.