= Beeren-Cheesecake

* Zubereitung: ca. 20 Minuten
* Backzeit: ca. 60 Minuten

== Zutaten

* 200 g Orangenkekse (z. B. Azora von Bahlsen)
* 100 g weiche Butter
* 4 Eier (Größe M)
* 200 g Zucker
* 100 ml Orangensaft
* 5 EL Speisestärke
* 800 g Frischkäse (Doppelrahm-Stufe)
* Salz
* 300 g Beeren-Mischung (TK)
* Puderzucker

== Zubereitung

- Den Backofen auf 160° Celsius (Umluft: 140° Celsius) vorheizen. Die
Orangenkekse fein zerbröseln, mit der Butter verkneten. Die Keksmasse
auf den Boden einer mit Backpapier ausgelegten Springform drücken und im
Kühlschrank kaltstellen.
- Die Eier trennen und die Eigelbe mit dem Zucker schaumig rühren. Den
Orangensaft, 3 EL Speisestärke und den Frischkäse einrühren. Die Eiweiße
mit einer Prise Salz steif schlagen und unter die Frischkäsemasse heben.
- Die Frischkäsemasse auf den Keks-Boden gießen. Die tiefgefrorenen
Beeren mit der restlichen Speisestärke bestäuben und gleichmäßig auf dem
Teig verteilen. Den Kuchen ca. 60 Minuten im Ofen backen. Erst nach dem
Auskühlen aus der Springform lösen und mit Puderzucker bestäubt
servieren.