= Engadiner Nusskuchen

* Zubereitung: ca. 45 Minuten
* Backen: ca. 45 Minuten
* Für 1 Springform mit 26 cm Durchmesser

== Zutaten

- 350 g Mehl
- 250 g Butter, weich
- 400 g Zucker
- 1 Prise Salz
- 1 Ei
- 1 Eigelb
- 400 g Walnüsse
- 100 g Schlagsahne
- 2 EL Honig

== Zubereitung

- Mehl, Butter, 200 g Zucker, Salz und das Ei verkneten und ca. 30 Minuten kalt
stellen. - Die Nüsse grob hacken. 200 g Zucker unter Rühren goldgelb
karamellisieren, gehackte Nüsse unterrühren und mit Sahne (bis auf einen TL)
ablöschen. Honig zugeben und ca. 1 Minute köcheln und abkühlen lassen.
- Teig auf wenig Mehl ca. 3 mm dick ausrollen. Zwei Kreise (26 cm Durchmesser)
ausschneiden. In eine mit Backpapier ausgelegte Springform (26 cm Durchmesser)
legen. Vier 20 cm lange Streifen (6 cm breit) ausschneiden. Innen an den
Springformrand legen und überhängen lassen.
Nusscreme einfüllen und übrige Teigplatte drauflegen. Rand überklappen, mit einer Gabel andrücken.
- Eigelb und 1 TL Sahne verquirlen und Torte mit 2/3 davon bestreichen. Im
vorgeheizten Backofen (175°Celsius / Umluft 150°C) 45-50 Minuten backen.

Quelle: https://www.chefkoch.de/rezepte/264181102553784/Engadiner-Nusstorte.html
