= Erdbeer-Basilikum-Torte

* Zubereitung: ca. 45 Minuten
* Kühlzeit: mindestens 4 Stunden
* Durchmesser ca. 26 cm

== Zutaten

* 300 g weiße Kuvertüre
* 25 g Kokosfett
* 50 g Mandelblättchen
* 100 g Cornflakes
* 2 Pck. gemahlene Gelatine
* 1 Bund Basilikum
* 300 g Vanillejoghurt
* 200 g Doppelrahm-Frischkäse
* 500 g Erdbeeren
* 400 g Schlagsahne
* 75-100 g Zucker

== Zubereitung

- Kuvertüre grob hacken, zusammen mit dem Kokosfett im heißen Wasserbad
schmelzen. Mandelblättchen in einer Pfanne ohne Fett rösten, mit den
Cornflakes unter die geschmolzene Kuvertüre heben. Auf eine Tortenplatte
einen Tortenring (26 cm Durchmesser) stellen, die Masse hineinfüllen und
darin glatt streichen, im Kühlschrank fest werden lassen.
- Gelatine nach Packungsangabe anrühren und erwärmen. Basilikum
abbrausen, trockenschütteln, Blättchen abzupfen. Einige zum Garnieren in
einem Schälchen mit Wasser beiseite stellen, die übrigen mit Joghurt und
Frischkäse mischen, pürieren. Aufgelöste Gelatine mit ein paar Löffeln
Creme verrühren, dann unter die übrige Crememasse ziehen. 10 Minuten
kalt stellen.
- Inzwischen Erdbeeren waschen, trockentupfen und putzen. Einige zum
Garnieren beiseite legen, restliche Erdbeeren würfeln. Sahne mit 1 EL
Zucker steif schlagen. Übrigen Zucker und geschlagene Sahne unter die
Joghurt-Frischkäse-Creme ziehen. Gewürfelte Erdbeeren unterheben. Masse
auf den Tortenboden geben und mindestens 4 Stunden kalt stellen. Vor dem
Servieren Tortenring entfernen und die Torte mit Basilikumblättern und
halbierten Erdbeeren garnieren.