= Faule Weiber - Kuchen


* Zubereitung: ca. 25 Minuten
* Backen: ca. 50 Minuten
* Springform mit 26cm Durchmesser   

== Zutaten
   
=== Für den Teig

* 200 g Mehl
* 75 g Zucker
* 1 Ei
* 75 g Margarine
* 1 TL Backpulver

=== Für den Belag

* 500 g Quark
* 2	Eier
* 140 g	Zucker
* 1 Pck. Vanillepuddingpulver
* 100 g Sauerrahm
* 80 ml Öl
* 240 ml Milch
* 1 kl. Dose Mandarinen
* 1 Pck. Tortenguss, klar



== Zubereitung

* Aus den Teigzutaten einen Mürbteig herstellen und in den Kühlschrank legen.

* Quark, Eier und Zucker in einer Rührschüssel von Hand rühren. Vanillepudding, Öl, Sauerrahm und Milch zusammenrühren und unter die Quarkmasse heben.

* Nach ca. 45 Minuten den Mürbteig ausrollen, in die Springform geben. Die Quarkmasse darauf geben und die Mandarinen darauf verteilen. Bei 180° Celsius Ober-/Unterhitze im vorgeheizten Backofen ca. 50 Minuten backen.

* Den Kuchen auskühlen lassen. Den Tortenguss nach Packungsanleitung zubereiten und den Kuchen damit überziehen.

---

Quelle: https://www.chefkoch.de/rezepte/78831030203242/Faule-Weiber-Kuchen.html
