= Quark-Streuselkuchen mit Kirschen

- Zubereitung: ca. 20 Minuten
- Backen: ca. 35 Minuten
- 1 Backblech

== Zutaten
   

=== Für den Teig

- 250 g Butter
- 250 g Zucker
- 1 Tüte Vanillezucker
- 1	Ei
- 1 Prise Salz
- 1 Tüte Backpulver
- 500 g Mehl


=== Für den Belag

- 1 kg Quark
- 1 Tüte Puddingpulver, Vanille
- 200 g Zucker
- 1 Ei
- 1/2 Zitrone, Saft
- 1 Glas Kirschen, abgetropft



== Zubereitung

- Die Butter schmelzen und abkühlen lassen. Für den Teig alle Teigzutaten mit den Knethaken krümelig rühren. 1/4 vom Teig zurück behalten. Den Rest des Teiges gleichmäßig auf ein mit Backpapier ausgelegtes Blech drücken.

- Die Zutaten für den Belag, außer die Kirschen, gut verrühren und auf den Teig streichen. Die Kirschen auf dem Belag verteilen und den Rest des Teiges wie Streusel darüber geben.

- Im vorgeheizten Ofen bei 175° Celsius 30 - 35 Minuten auf der mittleren Schiene backen.

---

Quelle: https://www.chefkoch.de/rezepte/844191189672411/Schneller-Quark-Streuselkuchen-mit-Obst.html
