= Rote-Bete-Schokokuchen

* Zubereitung: ca. 30 Minuten
* Backen: ca. 60 Minuten
* Für 1 Springform mit 28 cm Durchmesser

== Zutaten

=== Für den Schokoteig

* 300 g Rote Bete (vorgekocht, vakuumiert)
* 150 g Butter
* 100 g Zartbitterschokolade
* 3 Eier (Größe M)
* 150 g Zucker
* 150 g Mehl
* 1 gestrichener TL Backpulver
* 2 EL Kakaopulver, ungesüßt

=== Für die Käsekuchenmasse

* 2 Eier (Größe M)
* 100 g Zucker
* 50 ml Orangensaft
* 1 - 2 EL Speisestärke
* 400 g Doppelrahm-Frischkäse
* Puderzucker zum Bestäuben

== Zubereitung

* Den Backofen auf 180° Celsius (Umluft 160° Celsius) vorheizen. Rote
Beete grob würfeln, dann pürieren. Butter und Schokolade zusammen
zerlassen. Eier 5 bis 8 Minuten mit Zucker schaumig aufschlagen. Mehl,
Backpulver und Kakaopulver mischen, unterheben. Schokobutter und Rote
Bete-Püree in die Masse rühren. 5 EL Teig beiseitestellen, restlichen
Teig in die mit Backpapier ausgelegte Springform geben.
* Eier trennen. Eigelbe mit 50 g Zucker schaumig rühren. Orangensaft,
Speisestärke und Frischkäse einrühren. Eiweiß steif schlagen, restlichen
Zucker (50 g) einrieseln lassen. Eischnee unter die Frischkäsemasse
heben.
* Käsemasse auf den Schokoteig geben. Übrigen dunklen Teig darauf
verteilen, mit einer Gabel marmorieren. Kuchen im Ofen 60 Minuten
backen, evtl. die letzten 15 Minuten mit Alufolie abdecken. Abkühlen
lassen, mit Puderzucker bestäubt servieren.