= Kürbis-Hack-Auflauf

* Zubereitung: ca. 40 Minuten
* Backzeit: ca. 20 Minuten
* Pro Stück ca. 865 Kalorien

== Zutaten

* 2 Zwiebeln
* 2 EL Butter
* 400 g Rinderhackfleisch
* 240 g geschälte Tomaten (Fertigprodukt)
* Paprikapulver
* 400 g Penne
* 500 g Hokkaido-Kürbis
* 2 Pck. Bechamelsauce (Fertigprodukt, für insgesamt 500 ml)
* 1 Ei
* 100 g geriebener Käse

== Zubereitung

- Die Zwiebeln abziehen, fein würfeln und in 1 EL Butter glasig dünsten.
Das Hack zugeben und krümelig braten. Die Tomaten samt Saft angießen.
Mit Salz, Pfeffer und Paprikapulver würzen, 5 Minuten köcheln lassen.
- Inzwischen die Nudeln in Salzwasser nach Packungsangabe bissfest
garen, anschließend abgießen. Den Kürbis abwaschen, vierteln, entkernen
und mit einem Sparschäler etwa 5 cm lange Streifen abziehen. Den Kürbis
portionsweise in 1 EL heißer Butter 1 Minute dünsten, mit Salz und
Pfeffer würzen.
- Die Bechamelsauce nach Packungsangabe zubereiten und vom Herd nehmen.
Mit dem Ei und 50g geriebenen Käse verrühren.
- Den Backofen auf 200° Celsius (Umluft: 180° Celsius) vorheizen. Die
Auflaufform einfetten. Die Nudeln, den Kürbis und die Hacksauce
einschichten. Alles mit der hellen Sauce begießen, mit dem übrigen Käse
bestreuen und im Ofen ca. 20 Minuten überbacken. Nach Belieben mit
Petersilie garnieren.