= Lasagne

* Zubereitung: ca. 45 Minuten
* Backen: ca. 30 Minuten
* Für 6 Personen

== Zutaten

=== Bolognesesauce

* 2 Zwiebeln
* 2 Knoblauchzehen
* 2 Möhren
* 200 g Knollensellerie
* 6 EL Olivenöl
* 800 g Hackﬂeisch (vom Rind oder gemischt)
* 800 g stückige Tomaten (Dose)
* 1 Lorbeerblatt

=== Bechamelsauce

* 800 ml Milch
* 100 g Butter
* 4 EL Mehl
* Muskatnuss
* weißer Pfeffer
* Zitronensaft

=== Weitere Zutaten

* 200 g geriebener Parmesan
* 500 g Lasagneblätter (ohne Vorkochen)

== Zubereitung

- Zwiebeln, Knoblauch, Möhren und Sellerie schälen bzw. putzen, alles
klein würfeln. Öl erhitzen, erst Gemüse anbraten, dann Hackﬂeisch dazu
geben und mitbraten. Mit Tomaten und Lorbeerblatt zugedeckt 30 Minuten
einkochen lassen, gelegentlich umrühren. Lorbeerblatt entfernen, mit
Salz, Pfeffer und 1 Prise Zucker abschmecken.
- Butter in einer Pfanne oder Topf erhitzen, Mehl dazugeben. Das Gemisch
anschwitzen, bis es leicht bräunlich wird. Anschließend Milch peu a peu
dazugeben. Wenn die richtige Konsistenz gefunden ist, mit Zitronensaft,
Muskatnuss, weißem Pfeffer und Salz würzen.
- Backofen auf 200° Celsius (Umluft) vorheizen. Eine große, feuerfeste
Form mit Lasagneblättern auslegen, ein Drittel der Hackﬂeischsauce
darauf verteilen, etwas Bechamelsoße darüber geben. Rest weiter
einschichten, mit Lasagneblättern und Bechamelsoße abschließen.
Restlichen Parmesan darüber streuen. Im Backofen auf der mittleren
Schiene circa 30 Min. backen.