= Paprika-Pasta mit Mozzarella

* Zubereitung: ca. 30 Minuten
* Für 4 Portionen

== Zutaten

* 1 Zwiebel
* 2 Knoblauchzehen
* 3 Paprikaschoten (rot, gelb, grün)
* 500 g kleine Spiralnudeln
* 150 g Chorizo in dünnen Scheiben
* 300 g Mozzarella
* 3-4 EL Olivenöl
* 1 EL Paprikamark
* 200 ml Brühe

== Zubereitung

- Die Zwiebel und den Knoblauch abziehen, beides fein würfeln bzw.
hacken. Die Paprika halbieren, entkernen, waschen und klein würfeln. Die
Nudeln nach Packungsangabe in reichlich Salzwasser garen. Die
Chorizo-Scheiben eventuell halbieren. Den Mozzarella abtropfen lassen
und in Würfel schneiden.
- Das Olivenöl in einem großen Topf erhitzen, Zwiebel und Knoblauch
darin glasig dünsten. Die Paprika dazugeben und 3 bis 4 Minuten dünsten.
Das Paprikamark einrühren, mit der Gemüsebrühe ablöschen. Mit Salz,
Pfeffer und Zucker abschmecken.
- Die Nudeln abgießen, dabei etwas Kochwasser auffangen. Die Nudeln mit
der Paprika und der Chorizo mischen, eventuell 4 bis 5 EL Kochwasser
unterrühren. Den Mozzarella locker unterheben.