= Spaghetti mit Tomaten-Thunfisch-Sahne-Soße


* Zubereitung 15 Minuten
* Kochzeit 10 Minuten
* Für 4 Personen

== Zutaten

- 2 Zwiebeln
- 2 Knoblauchzehen
- 2 EL Olivenöl
- 1 Dose Thunfisch, in Öl
- 1 Dose Tomaten (Pizzatomaten)
- 1 Peperoncini, klein
- 1 Becher Sahne
- 1/2 TL Salz und Pfeffer
- 500 g Spaghetti
- 2 EL Parmesan, gerieben

== Zubereitung

- Den Knoblauch schälen und pressen. Die Zwiebeln in Würfel schneiden. Die Pepperoncini ebenfalls zerkleinern.
- Das Olivenöl in einen Topf geben und erhitzen. Anschließend den gepressten Knoblauch hinein geben und so lange anbraten, bis er bräunlich wird.
- Die Zwiebeln hinzugeben und leicht anbraten. Sind die Zwiebeln leicht glasig, den Thunfisch dazu, zerkleinern und mit anbraten.
- Die Pizzatomaten und die zerkleinerten Pepperoncini hinzu, gut umrühren und ca. 10 Minuten kochen lassen.
- Die Sahne zufügen und mit Pfeffer und Salz abschmecken.
- Die Spaghetti al dente kochen, abseihen und mit etwas Olivenöl übergießen.

Quelle: https://www.chefkoch.de/rezepte/260591101751682/Spaghetti-mit-Thunfisch-Sahne-Sosse.html
