= Thunfisch - Nudelauflauf


- Zubereitung 20 Minuten
- Backzeit 20 Minuten
- Für 3 Personen

== Zutaten

- 250 g	Nudeln
- 2 Dosen	Thunfisch im eigenen Saft
- 1 Becher Sahne
- 200 ml Milch
- 3 EL Tomatenmark
- 100 g	Sahne-Schmelzkäse
- 2 mittelgroße	Zwiebeln
- 2 EL Öl
- 150 g	Käse, gerieben
- Chilipulver
- Paprikapulver

== Zubereitung

- Nudeln im Salzwasser nach Packungsanweisung -noch nicht ganz- al dente kochen.
Die Zwiebeln schälen und klein würfeln. Anschließend in Öl anbraten, bis sie
eine leichte braune Farbe haben. Sahne, Milch, Tomatenmark und Sahneschmelzkäse
dazugeben und unter Rühren köcheln lassen, bis der Käse geschmolzen ist.

- Mit Pfeffer, Salz, Chili und Paprikapulver abschmecken. Sollte die Soße noch
zu flüssig sein, etwas Schmand zugeben.

- Die Nudeln in eine Auflaufform geben. Den Thunfisch aus der Dose in den Nudeln
verteilen.

- Die Soße darübergeben und mit Käse reichlich bestreuen. Bei ca. 180°C in den
Backofen geben, bis der Käse schön verlaufen und leicht angebräunt ist.

Quelle:
https://www.chefkoch.de/rezepte/1106351216730859/Thunfisch-Nudelauflauf.html