= Joghurtmuffins mit Pflaumen

- Zubereitung: ca. 20 Minuten
- Backzeit: ca. 25 Minuten
- Für 12 Stück

== Zutaten

- 400 g Pflaumen
- 250 g Mehl
- 1/2 Pck. Backpulver
- 1 Prise Salz
- 125 g Puderzucker
- 2 m.-große Eier
- 75 ml Öl
- 150 g Sahnejoghurt
- 1 Bio-Orange(n), abgeriebene Schale und Saft davon

== Zubereitung

- Pflaumen waschen, entsteinen und in kleine Stücke schneiden.

- Mehl, Backpulver, Salz und Zucker in einer großen Rührschüssel mischen. Eier, Öl, Jogurt, Orangenschale und 5 Esslöffel Orangensaft verquirlen und mit einem Löffel kurz unter das Mehl rühren, bis alles gerade verrührt ist. Der Teig soll nicht geschmeidig sein. Pflaumen unterheben.

- In die 12 Mulden einer Muffin-Form Papiermanschetten legen oder diese fetten. Teig hinein füllen.

- Im vorgeheizten Backofen bei 175 °C Ober-/Unterhitze (Umluft: 150 °C) ca. 25 - 30 Minuten goldbraun backen. Auf einem Kuchengitter auskühlen lassen.

---

Quelle: https://www.chefkoch.de/rezepte/1790671289386858/Joghurtmuffins-mit-Pflaumen.html